"use client";
import {useEffect,useState} from "react";
import {supabase} from "@/utils/supabase/client";
import {targetLanguage} from "@/utils/targetLanguage";
import TopicCardModal,{type Detail} from "@/components/ideas/TopicCardModal";
import {wishWords,type WishPresentation} from "@/components/cards/PersonalWishSummary";
export function targetLabels(type?:string|null){const words=targetLanguage(type);return [words.want,words.done]}
export default function CanonicalTargetPeople({seedId,targetId,seedType,compact=false,presentation}:{seedId?:string|null;targetId?:string|null;seedType?:string|null;initialCounts?:[number,number];compact?:boolean;socialCount?:number;socialHref?:string;presentation?:WishPresentation}){
 const [detail,setDetail]=useState<(Detail&{communityCounts?:number[];contentType?:{id:string;label:string;icon:string;base_kind:string;ui_labels?:WishPresentation["ui_labels"]}})|null>(null),[resolved,setResolved]=useState(targetId||""),[error,setError]=useState(false),[retry,setRetry]=useState(0),[view,setView]=useState<"want"|"done"|"events"|null>(null);
 useEffect(()=>{let alive=true;setError(false);setDetail(null);void(async()=>{try{let id=targetId;if(!id&&seedId){const result=await supabase.rpc("get_canonical_seed_detail_v31",{p_source_seed_id:seedId});if(result.error)throw result.error;const row=Array.isArray(result.data)?result.data[0]:result.data;id=row?.canonical_target_id;}if(!id)throw new Error("Kart bulunamadı");const response=await fetch("/api/ideas/"+encodeURIComponent(id)+"?summary=1",{cache:"no-store"});if(!response.ok)throw new Error("Kart yüklenemedi");const data=await response.json();if(alive){setResolved(id);setDetail(data)}}catch{if(alive)setError(true)}})();return()=>{alive=false}},[targetId,seedId,retry]);
 const type=detail?.contentType;const p=presentation||(type?{type_id:type.id,type_label:type.label,type_icon:type.icon,base_kind:type.base_kind,ui_labels:type.ui_labels,start_date:null,end_date:null,timing_precision:"flexible",date_options:[],location:null}:null);
 const fallback=targetLanguage(seedType);const w=p?wishWords(p):null;const contextual=w&&(w.action!=="YAP"||Boolean(p?.ui_labels?.wanting)||!seedType);const wanting=contextual?w.wanting:fallback.want,doers=contextual?w.doers:fallback.done;const today=new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Istanbul"});
 const counts=detail?.communityCounts||(detail?[detail.people.filter(p=>p.is_current!==false).length,detail.reviews.length,detail.events.filter(e=>!["cancelled","canceled","completed"].includes(e.status||"")&&!["cancelled","completed"].includes(e.plan_status||"")&&(!e.end_date||e.end_date.slice(0,10)>=today)).length]:null);
 return <><div className="grid grid-cols-3 gap-2">{(["want","done","events"] as const).map((v,i)=><button key={v} type="button" disabled={!detail} onClick={()=>setView(v)} className={"rounded-xl border px-2 py-3 text-left text-xs "+(i===0?"border-emerald-100 bg-emerald-50 text-emerald-900":"border-violet-100 bg-violet-50 text-violet-900")}><span className="block min-h-8 text-[11px] leading-4">{[wanting,doers,"Aktif etkinlikler"][i]}</span><span className={compact?"font-bold":"block text-xl font-black"}>{counts?counts[i]:error?"—":"…"}</span></button>)}</div>{error&&<button type="button" onClick={()=>setRetry(r=>r+1)} className="text-xs text-red-700 underline">Sayaçları tekrar yükle</button>}{view&&detail&&<TopicCardModal selected={{catalogItemId:detail.card.catalog_item_id||"",canonicalTargetId:resolved,title:detail.card.title,subtitle:detail.card.subtitle,coverUrl:detail.card.cover_url,initialView:view}} contentType={{id:p?.type_id||seedType||"activity",label:p?.type_label||"Aktivite",icon:p?.type_icon||fallback.icon}} isClub={p?.base_kind==="club"} mediaKind={p?.base_kind==="movie"?"movie":p?.base_kind==="series"||p?.base_kind==="video"?"series":undefined} wantingLabel={wanting} doersLabel={doers} wantLabel={contextual?w.want:(fallback.want.replace(" isteyenler"," istiyorum"))} doneLabel={w?.done||"Deneyim ekle"} targetAction={contextual?w.action:fallback.action} eventButtonLabel={w?.event||"Etkinlik düzenle"} onSelectType={id=>{window.location.href="/ideas?kind="+encodeURIComponent(id)}} onClose={()=>{setView(null);setRetry(r=>r+1)}}/>}</>;
}
