"use client";
import {useState} from "react";
import CanonicalTargetPeople from "@/components/seeds/CanonicalTargetPeople";
import PersonalLibraryCard from "@/components/cards/PersonalLibraryCard";
import TopicCardModal from "@/components/ideas/TopicCardModal";
import {commonIntentTitle} from "@/utils/commonIntentTitle";
import {wishBadge,wishHow,wishWhen,wishWords,type WishPresentation} from "@/components/cards/PersonalWishSummary";
import type {ClubProfile} from "@/utils/clubProfile";
export type MyPersonalIntent=WishPresentation & {club_profile?:ClubProfile|null;cover_position_y?:number;has_completed_experience?:boolean;id:string;target_id:string;title:string;subtitle:string|null;cover_url:string|null;catalog_item_id:string|null;start_date:string|null;end_date:string|null;timing_precision:string;date_options:string[];location:string|null;notes:string|null;created_at:string;type_id:string;type_label:string;type_icon:string;base_kind:string};
export default function MyPersonalIntentCard({intent}:{intent:MyPersonalIntent}){
 const [open,setOpen]=useState<"overview"|"want_form"|null>(null);const title=commonIntentTitle(intent.title);const words=wishWords(intent);const expired=Boolean(intent.end_date&&intent.end_date.slice(0,10)<new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date()));
 const wantText=intent.has_completed_experience&&(intent.base_kind==="movie"||intent.base_kind==="series")?"Yeniden izlemek istiyorum":words.want;
 return <><PersonalLibraryCard title={title} subtitle={intent.subtitle} coverUrl={intent.cover_url} coverPositionY={intent.cover_position_y} badge={wishBadge(intent)} icon={intent.type_icon} onOpen={()=>setOpen("overview")} summary={<div className="space-y-1.5"><p className="font-black text-emerald-300">{wishHow(intent)||wantText}</p><p>📅 {wishWhen(intent)}</p><p className="line-clamp-1">📍 {intent.location||"Konum belirlemedim"}</p>{expired&&<p className="font-bold text-amber-300">Süresi geçti · Tarihini yenileyebilirsin</p>}</div>} metrics={<CanonicalTargetPeople targetId={intent.target_id} presentation={intent} appearance="overlay"/>} action={<button onClick={()=>setOpen("want_form")} className="min-h-[58px] w-full rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white hover:bg-emerald-700">✓<span className="mt-1 block">{expired?"İsteğimi yenile":"İsteğimi düzenle"}</span></button>}/>{open&&<TopicCardModal isClub={intent.base_kind==="club"} mediaKind={intent.base_kind==="movie"?"movie":intent.base_kind==="series"||intent.base_kind==="video"?"series":undefined} eventButtonLabel={words.event} selected={{catalogItemId:intent.catalog_item_id||"",canonicalTargetId:intent.target_id,title,subtitle:intent.subtitle,coverUrl:intent.cover_url,initialView:open||"overview"}} wantLabel={words.want} doneLabel={words.done} wantingLabel={words.wanting} doersLabel={words.doers} targetAction={words.action} contentType={{id:intent.type_id,label:intent.type_label,icon:intent.type_icon}} onSelectType={()=>{window.location.href="/ideas?kind="+encodeURIComponent(intent.type_id)}} onClose={()=>setOpen(null)}/>}</>;
}
