"use client";
import {useState} from "react";
import CanonicalTargetPeople from "@/components/seeds/CanonicalTargetPeople";
import UinCard from "@/components/cards/UinCard";
import TopicCardModal from "@/components/ideas/TopicCardModal";
import {commonIntentTitle} from "@/utils/commonIntentTitle";
import PersonalWishSummary,{wishBadge,wishHow,wishWords,type WishPresentation} from "@/components/cards/PersonalWishSummary";
import type {ClubProfile} from "@/utils/clubProfile";
export type MyPersonalIntent=WishPresentation & {club_profile?:ClubProfile|null;cover_position_y?:number;has_completed_experience?:boolean;id:string;target_id:string;title:string;subtitle:string|null;cover_url:string|null;catalog_item_id:string|null;start_date:string|null;end_date:string|null;timing_precision:string;date_options:string[];location:string|null;notes:string|null;created_at:string;type_id:string;type_label:string;type_icon:string;base_kind:string};
export default function MyPersonalIntentCard({intent}:{intent:MyPersonalIntent}){
 const [open,setOpen]=useState<"overview"|"want_form"|null>(null);const title=commonIntentTitle(intent.title);const words=wishWords(intent);const expired=Boolean(intent.end_date&&intent.end_date.slice(0,10)<new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date()));
 return <><UinCard title={title} controls={<button type="button" onClick={()=>setOpen("overview")} aria-label={title+" kartını aç"} className="rounded-full bg-white/90 px-3 py-2 text-sm">👁</button>} subtitle={intent.subtitle} coverUrl={intent.cover_url} coverPositionY={intent.cover_position_y} category={wishHow(intent)||words.action} icon={intent.type_icon} badge={wishBadge(intent)} tone="target" primary={<button onClick={()=>setOpen("want_form")} className="w-full rounded-xl bg-emerald-600 px-3 py-3 text-xs font-bold text-white">{expired?"İsteğimi yenile":"İsteğimi düzenle"}</button>}>{expired&&<p className="mb-3 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900">Hâlâ yapmak istiyor musun? Tarihini güncelle veya isteğini arşivle.</p>}<PersonalWishSummary presentation={intent} wantLabel={intent.has_completed_experience&&(intent.base_kind==="movie"||intent.base_kind==="series")?"Yeniden izlemek istiyorum":undefined} notes={intent.notes}/><div className="mt-3"><CanonicalTargetPeople targetId={intent.target_id} presentation={intent}/></div></UinCard>{open&&<TopicCardModal isClub={intent.base_kind==="club"} mediaKind={intent.base_kind==="movie"?"movie":intent.base_kind==="series"||intent.base_kind==="video"?"series":undefined} eventButtonLabel={words.event} selected={{catalogItemId:intent.catalog_item_id||"",canonicalTargetId:intent.target_id,title,subtitle:intent.subtitle,coverUrl:intent.cover_url,initialView:open||"overview"}} wantLabel={words.want} doneLabel={words.done} wantingLabel={words.wanting} doersLabel={words.doers} targetAction={words.action} contentType={{id:intent.type_id,label:intent.type_label,icon:intent.type_icon}} onSelectType={()=>{window.location.href="/ideas?kind="+encodeURIComponent(intent.type_id)}} onClose={()=>setOpen(null)}/>}</>;
}
