"use client";
import {useState,useEffect} from "react";
import {supabase} from "@/utils/supabase/client";
import CanonicalTargetPeople from "@/components/seeds/CanonicalTargetPeople";
import TopicCardModal,{type Detail} from "@/components/ideas/TopicCardModal";
export type Proposal={id:string;target_id:string;title:string;sender_name:string;recipient_name:string;is_sender:boolean;proposed_date:string|null;place:string;preference:string;note:string;status:string;created_at:string};
export default function TogetherInbox({initial}:{initial:Proposal[]}){const [items,setItems]=useState(initial),[busy,setBusy]=useState(""),[error,setError]=useState("");async function answer(p:Proposal,accept:boolean){setBusy(p.id);setError("");try{const {error:e}=await supabase.rpc("answer_uin_together_v71",{p_id:p.id,p_accept:accept});if(e)setError(e.message);else setItems(rows=>rows.map(r=>r.id===p.id?{...r,status:accept?"accepted":"declined"}:r));}catch{setError("Yanıt kaydedilemedi. Tekrar deneyebilirsin.")}finally{setBusy("")}}
 return <><h1 className="text-3xl font-black">Birlikte yapma önerilerim</h1>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}{!items.length&&<p className="mt-6 rounded-2xl border bg-white p-6 text-slate-500">Henüz öneri yok. Kartlardan isteyenleri açıp bir arkadaşına birlikte yapmayı önerebilirsin.</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{items.map(p=><article key={p.id} className="space-y-3 rounded-3xl border bg-white p-6"><p className="text-xs font-bold text-emerald-800">{p.is_sender?"Gönderdiğin öneri":"Gelen öneri"} · {p.status==="pending"?"Yanıt bekliyor":p.status==="accepted"?"Kabul edildi":"Kabul edilmedi"}</p><h2 className="text-xl font-black">{p.title}</h2><p className="text-sm">{p.is_sender?p.recipient_name:p.sender_name}</p><dl className="space-y-2 text-sm"><div><dt className="text-xs text-slate-500">Ne zaman?</dt><dd>{p.proposed_date?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium"}).format(new Date(p.proposed_date+"T12:00:00")):"Birlikte belirlenecek"}</dd></div><div><dt className="text-xs text-slate-500">Nerede?</dt><dd>{p.place||"Birlikte belirlenecek"}</dd></div>{p.preference&&<div><dt className="text-xs text-slate-500">Nasıl?</dt><dd>{p.preference}</dd></div>}</dl>{p.note&&<p className="whitespace-pre-line text-sm text-slate-600">{p.note}</p>}{!p.is_sender&&p.status==="pending"&&<div className="flex gap-3"><button disabled={busy===p.id} onClick={()=>void answer(p,true)} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">Kabul et</button><button disabled={busy===p.id} onClick={()=>void answer(p,false)} className="rounded-xl border px-4 py-3 text-sm">Kabul etme</button></div>}{p.status==="accepted"&&<AcceptedPlan proposal={p}/>}<CanonicalTargetPeople targetId={p.target_id}/></article>)}</div></>}
function AcceptedPlan({proposal:p}:{proposal:Proposal}){const [open,setOpen]=useState(false);return <><button type="button" onClick={()=>setOpen(true)} className="rounded-xl bg-violet-700 px-4 py-3 text-sm font-bold text-white">Birlikte etkinlik planla</button>{open&&<ProposalEvent targetId={p.target_id} date={p.proposed_date} onClose={()=>setOpen(false)}/>}</>}
function ProposalEvent({targetId,date,onClose}:{targetId:string;date:string|null;onClose:()=>void}){const [data,setData]=useState<(Detail&{contentType?:{id:string;label:string;icon:string;base_kind:string}})|null>(null),[error,setError]=useState(false);useEffect(()=>{let alive=true;void fetch("/api/ideas/"+targetId,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Kart yüklenemedi");return r.json()}).then(d=>{if(alive)setData(d)}).catch(()=>{if(alive)setError(true)});return()=>{alive=false}},[targetId]);if(!data)return <p>{error?"Etkinlik kartı yüklenemedi. Yeniden deneyebilirsin.":"Etkinlik kartı yükleniyor…"} <button onClick={onClose}>Kapat</button></p>;const t=data.contentType||{id:"activity",label:"Aktivite",icon:"✨",base_kind:"activity"};return <TopicCardModal selected={{catalogItemId:data.card.catalog_item_id||"",canonicalTargetId:targetId,title:data.card.title,subtitle:data.card.subtitle,coverUrl:data.card.cover_url,initialView:"event_form",initialStartDate:date||undefined}} isClub={t.base_kind==="club"} mediaKind={t.base_kind==="movie"?"movie":t.base_kind==="series"?"series":undefined} contentType={t} wantLabel="İstiyorum" doneLabel="Deneyim ekle" targetAction="YAP" onClose={onClose} onSelectType={id=>{window.location.href="/ideas?kind="+id}}/>}
