"use client";
import {useState} from "react";
import {supabase} from "@/utils/supabase/client";
export default function TogetherProposal({targetId,recipientId,name,title,initialDate,initialPlace,initialPreference}:{targetId:string;recipientId:string;name:string;title:string;initialDate?:string|null;initialPlace?:string|null;initialPreference?:string|null}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[message,setMessage]=useState("");const [date,setDate]=useState(initialDate?.slice(0,10)||""),[place,setPlace]=useState(initialPlace||""),[preference,setPreference]=useState(initialPreference||""),[note,setNote]=useState("");
 async function prepare(){setBusy(true);setMessage("");try{const {data,error}=await supabase.rpc("prepare_uin_together_v71",{p_target_id:targetId,p_recipient_id:recipientId});if(error)throw error;if(data?.allowed)setOpen(true);else setMessage(data?.reason||"Öneri gönderilemiyor.")}catch{setMessage("Öneri açılamadı. Tekrar deneyebilirsin.")}finally{setBusy(false)}}
 async function send(){setBusy(true);setMessage("");try{const {error}=await supabase.rpc("send_uin_together_v71",{p_target_id:targetId,p_recipient_id:recipientId,p_date:date||null,p_place:place,p_preference:preference,p_note:note});if(error)throw error;setSent(true);setOpen(false);setMessage("Önerin gönderildi. Yanıtını Birlikte yapma önerilerim bölümünden görebilirsin.")}catch(e){setMessage(e instanceof Error?e.message:(e as {message?:string})?.message||"Öneri gönderilemedi.")}finally{setBusy(false)}}
 const field="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900";
 return <div className="min-w-36"><button type="button" disabled={busy||sent} onClick={()=>void prepare()} className="rounded-xl border border-emerald-200 bg-white px-3 py-2 text-xs font-bold text-emerald-800 disabled:opacity-60">{sent?"✓ Öneri gönderildi":busy?"Yükleniyor…":"Birlikte yapmayı öner"}</button>{open&&<div role="dialog" aria-label="Birlikte yapma önerisi" className="fixed inset-0 z-[150] overflow-y-auto bg-black/60 p-4"><section className="mx-auto my-8 max-w-lg space-y-4 rounded-3xl bg-white p-6 text-left shadow-xl"><h3 className="text-xl font-black">Birlikte yapmayı öner</h3><p className="text-sm"><b>{name}</b> · {title}</p><label className="block text-xs font-bold">Tarih (isteğe bağlı)<input type="date" min={new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Istanbul"})} value={date} onChange={e=>setDate(e.target.value)} className={field}/></label><label className="block text-xs font-bold">Nerede?<input maxLength={300} value={place} onChange={e=>setPlace(e.target.value)} className={field} placeholder="Birlikte belirleyebiliriz"/></label><label className="block text-xs font-bold">Nasıl?<input maxLength={300} value={preference} onChange={e=>setPreference(e.target.value)} className={field}/></label><label className="block text-xs font-bold">Notun<textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} className={field} placeholder="Birlikte ne yapmak istediğini yaz…"/></label><p className="text-xs text-slate-500">Kişi önerini yanıtlayabilir; kabul edilirse birlikte bir etkinlik planlayabilirsiniz.</p>{message&&<p role="alert" className="text-sm text-red-700">{message}</p>}<div className="flex gap-3"><button type="button" disabled={busy} onClick={()=>void send()} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white">{busy?"Gönderiliyor…":"Öneriyi gönder"}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-3 text-sm">Vazgeç</button></div></section></div>}{message&&!open&&<p role="status" className="mt-2 text-xs text-slate-600">{message}</p>}</div>;
}
