"use client";
import {useEffect,useState,type ReactNode} from 'react';
type Item={externalId:string;title:string;coverUrl?:string|null;sourceUrl?:string|null;creatorName?:string|null;metadata:{genres?:string[];followers?:number|null;popularity?:number|null;spotify_images?:string[];release_date?:string;album_type?:string;total_tracks?:number;duration_ms?:number;explicit?:boolean;track_number?:number;disc_number?:number;isrc?:string|null}};
type Data={artist:Item;albums:Item[];albumTotal:number;nextOffset:number|null;topTracks?:Item[];relatedArtists?:Item[];availability?:{albums:number;topTracks:number|null;relatedArtists:number|null};album?:Item;albumDetails?:{label?:string|null;copyrights?:string[]};tracks?:Item[];trackTotal?:number;candidates?:Item[];error?:string};
function duration(ms?:number){if(!ms)return '';const sec=Math.floor(ms/1000);return Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0')}
function Link({item,children}:{item:Item;children:React.ReactNode}){return <a href={item.sourceUrl||'https://open.spotify.com/'+(item.metadata.album_type?'album':'artist')+'/'+item.externalId} target="_blank" rel="noopener noreferrer" className="hover:text-emerald-700 hover:underline">{children}</a>}
function Tracks({items}:{items:Item[]}){return <ol className="mt-3 divide-y rounded-xl border">{items.map(item=><li key={item.externalId} className="flex items-center gap-3 p-3 text-sm"><span className="flex-1"><Link item={item}><span className="font-semibold">{item.title}</span></Link>{item.metadata.explicit&&<span className="ml-2 rounded bg-slate-100 px-1 text-[10px]">E</span>}{item.creatorName&&<span className="mt-1 block text-xs text-slate-500">{item.creatorName}</span>}</span><span className="text-xs text-slate-500">{duration(item.metadata.duration_ms)}</span></li>)}</ol>}
export default function SpotifyArtistPanel({targetId,artistId,headerAction}:{targetId?:string;artistId?:string;headerAction?:ReactNode}){
 const [data,setData]=useState<Data|null>(null),[album,setAlbum]=useState<Data|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[candidates,setCandidates]=useState<Item[]>([]),[retry,setRetry]=useState(0),[chosen,setChosen]=useState(artistId||'');
 useEffect(()=>{setChosen(artistId||'')},[artistId,targetId]);
 const params=(offset=0,albumId='')=>new URLSearchParams({...targetId?{targetId}:{},...(chosen||artistId||data?.artist?.externalId)?{artistId:chosen||artistId||data!.artist.externalId}:{},offset:String(offset),...albumId?{albumId}:{}});
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setData(null);setAlbum(null);setCandidates([]);void fetch('/api/spotify/artist?'+params(),{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok){setCandidates(d.candidates||[]);throw Error(d.error||'Spotify bilgileri alınamadı.')}setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[targetId,artistId,chosen,retry]);
 async function more(){if(data?.nextOffset==null)return;setBusy(true);setError('');try{const r=await fetch('/api/spotify/artist?'+params(data.nextOffset));const d=await r.json();if(!r.ok)throw Error(d.error);setData(old=>old?{...old,albums:[...old.albums,...d.albums.filter((x:Item)=>!old.albums.some(a=>a.externalId===x.externalId))],nextOffset:d.nextOffset}:d)}catch{setError('Diğer albümler yüklenemedi. Tekrar deneyebilirsin.')}finally{setBusy(false)}}
 async function openAlbum(item:Item,offset=0){setBusy(true);setError('');try{const r=await fetch('/api/spotify/artist?'+params(offset,item.externalId));const d=await r.json();if(!r.ok)throw Error(d.error);setAlbum(old=>offset&&old?{...d,tracks:[...(old.tracks||[]),...(d.tracks||[])]}:d)}catch{setError('Albüm şarkıları yüklenemedi. Tekrar deneyebilirsin.')}finally{setBusy(false)}}
 return <section className="mt-5 space-y-4 rounded-2xl border border-emerald-100 bg-white p-4"><div className="flex items-center gap-2"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-6 w-6 fill-[#1DB954]"><path d="M12 0a12 12 0 100 24 12 12 0 000-24zm5.5 17.3a.75.75 0 01-1 .25c-2.85-1.75-6.44-2.14-10.66-1.17a.75.75 0 01-.34-1.46c4.62-1.06 8.59-.61 11.78 1.35a.75.75 0 01.22 1.03zm1.43-3.18a.94.94 0 01-1.29.31c-3.26-2-8.23-2.58-12.08-1.4a.94.94 0 01-.55-1.79c4.4-1.35 9.88-.7 13.61 1.6a.94.94 0 01.31 1.28zm.12-3.31C15.14 8.49 8.69 8.27 4.96 9.4a1.13 1.13 0 01-.65-2.16c4.28-1.3 11.4-1.05 15.91 1.63a1.13 1.13 0 01-1.17 1.94z"/></svg><h3 className="font-black">Spotify’da sanatçı</h3></div>
 {busy&&!data&&<p className="text-sm text-slate-500">Sanatçı ve müzikleri yükleniyor…</p>}{error&&<div role="status" className="text-sm text-slate-600"><p>{error}</p><button type="button" onClick={()=>setRetry(n=>n+1)} className="mt-2 font-bold text-emerald-700">Tekrar dene</button></div>}{candidates.length>0&&<div className="space-y-2">{candidates.map(item=><button type="button" key={item.externalId} onClick={()=>setChosen(item.externalId)} className="flex w-full items-center gap-3 rounded-xl border p-3 text-left">{item.coverUrl&&<img src={item.coverUrl} alt="" className="h-14 w-14 object-contain"/>}{item.title}</button>)}</div>}
 {data&&<><div className="flex flex-wrap items-center gap-4">{data.artist.coverUrl&&<Link item={data.artist}><img src={data.artist.coverUrl} alt={data.artist.title} className="h-28 w-28 object-contain"/></Link>}<div className="min-w-0 flex-1"><Link item={data.artist}><h4 className="text-lg font-black">{data.artist.title} ↗</h4></Link>{Boolean(data.artist.metadata.genres?.length)&&<p className="mt-1 text-sm text-slate-600">{data.artist.metadata.genres?.join(' · ')}</p>}{data.artist.metadata.followers!=null&&<p className="mt-1 text-xs text-slate-500">{data.artist.metadata.followers.toLocaleString('tr-TR')} takipçi</p>}{data.artist.metadata.popularity!=null&&<p className="mt-1 text-xs text-slate-500">Spotify popülerliği: {data.artist.metadata.popularity}/100</p>}<p className="mt-3 text-sm font-bold text-emerald-700"><Link item={data.artist}>Spotify’da aç ↗</Link></p></div>{headerAction&&<div className="flex w-full flex-wrap items-center gap-3 sm:ml-auto sm:w-auto">{headerAction}</div>}</div>
 {(data.artist.metadata.spotify_images?.length||0)>1&&<details><summary className="cursor-pointer text-xs font-bold text-slate-600">Diğer sanatçı fotoğrafları</summary><div className="mt-3 flex flex-wrap gap-3">{data.artist.metadata.spotify_images?.slice(1).map(url=><Link key={url} item={data.artist}><img src={url} alt={data.artist.title} className="h-24 w-24 object-contain"/></Link>)}</div></details>}
 {data.topTracks?.length? <div><h4 className="font-black">Popüler şarkılar</h4><Tracks items={data.topTracks}/></div>:null}
 <div><h4 className="font-black">Albümler ve single’lar{data.albumTotal>0&&<span className="ml-2 text-xs font-normal text-slate-500">{data.albumTotal} yayın</span>}</h4>{!data.albums.length&&<p className="mt-2 text-sm text-slate-500">{data.availability?.albums===200?'Bu kaynakta yayın bulunamadı.':'Spotify albüm bilgisine şu anda erişilemiyor.'}</p>}<div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.albums.map(item=><article key={item.externalId} className="flex min-w-0 items-start gap-3 rounded-xl border border-slate-200 p-3">{item.coverUrl&&<div className="shrink-0"><Link item={item}><img src={item.coverUrl} alt={item.title} className="h-20 w-20 rounded-lg object-contain"/></Link></div>}<div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-bold leading-snug"><Link item={item}>{item.title} ↗</Link></p><p className="mt-1 text-[11px] leading-4 text-slate-500">{item.metadata.release_date} · {item.metadata.album_type==='single'?'Single':item.metadata.album_type==='compilation'?'Derleme':'Albüm'}{item.metadata.total_tracks!=null&&' · '+item.metadata.total_tracks+' şarkı'}</p><button type="button" disabled={busy} onClick={()=>void openAlbum(item)} className="mt-2 text-xs font-bold text-emerald-700 disabled:opacity-40">Şarkıları gör</button></div></article>)}</div>{data.nextOffset!=null&&<button type="button" disabled={busy} onClick={()=>void more()} className="mt-3 rounded-xl border px-4 py-2 text-sm font-bold">{busy?'Yükleniyor…':'Daha fazla yayın göster'}</button>}</div>
 {album?.album&&<div className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><h4 className="font-black">{album.album.title}</h4><button type="button" onClick={()=>setAlbum(null)} aria-label="Albüm şarkılarını kapat">×</button></div>{album.albumDetails?.label&&<p className="mt-1 text-xs text-slate-500">{album.albumDetails.label}</p>}<Tracks items={album.tracks||[]}/>{album.nextOffset!=null&&<button type="button" disabled={busy} onClick={()=>void openAlbum(album.album!,album.nextOffset!)} className="mt-3 text-xs font-bold text-emerald-700">Diğer şarkıları göster</button>}{album.albumDetails?.copyrights?.map(text=><p key={text} className="mt-2 text-[10px] text-slate-500">{text}</p>)}</div>}
 {Boolean(data.relatedArtists?.length)&&<div><h4 className="font-black">Benzer sanatçılar</h4><div className="mt-3 flex flex-wrap gap-3">{data.relatedArtists?.map(item=><Link key={item.externalId} item={item}><span className="text-sm">{item.title} ↗</span></Link>)}</div></div>}
 <p className="text-[10px] text-slate-500">Kaynak: Spotify. Konser takvimi ve biyografi bu bağlantı üzerinden sunulmuyor.</p></>}
 </section>;
}
