import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/utils/supabase/server';
export async function GET(request:NextRequest){
 try{const db=await createClient();let artistId=request.nextUrl.searchParams.get('artistId')||'';const targetId=request.nextUrl.searchParams.get('targetId')||'';const albumId=request.nextUrl.searchParams.get('albumId')||'';let query='';
 if(artistId&&!/^[a-zA-Z0-9]{22}$/.test(artistId)||albumId&&!/^[a-zA-Z0-9]{22}$/.test(albumId))return NextResponse.json({error:'Geçerli bir Spotify sanatçısı seç.'},{status:400});
 if(targetId){if(!/^[0-9a-f-]{36}$/i.test(targetId))return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const profile=await db.rpc('get_uin_card_profile_v60',{p_target_id:targetId});const card=profile.data as {title?:string;metadata?:Record<string,unknown>}|null;if(profile.error||!card?.title)return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const catalogue=await db.from('seed_catalog_items').select('external_id,external_source,item_kind,metadata').eq('canonical_target_id',targetId).eq('status','active');const item=catalogue.data?.find(item=>item.external_source==='spotify')||catalogue.data?.[0];const metadata={...(item?.metadata||{}),...(card.metadata||{})} as Record<string,unknown>;const typeId=String(metadata.content_type_id||item?.item_kind||'');const type=await db.from('uin_content_types').select('base_kind').eq('id',typeId).maybeSingle();if(type.data?.base_kind!=='artist'&&item?.item_kind!=='artist')return NextResponse.json({error:'Bu kart bir müzik sanatçısı değil.'},{status:400});query=card.title.slice(0,160);if(!artistId){const candidate=String(metadata.spotify_id||(item?.external_source==='spotify'?item.external_id:'')||'');if(/^[a-zA-Z0-9]{22}$/.test(candidate))artistId=candidate;}}
 if(!artistId&&!query)return NextResponse.json({error:'Bir sanatçı seç.'},{status:400});const offset=Math.max(0,Math.min(10000,Math.floor(Number(request.nextUrl.searchParams.get('offset'))||0)));
 const {data,error}=await db.functions.invoke('uin-spotify-search',{body:{action:'artist',artistId:artistId||null,query:query||null,albumId:albumId||null,offset},...(process.env.SUPABASE_FUNCTION_ANON_KEY?{headers:{Authorization:'Bearer '+process.env.SUPABASE_FUNCTION_ANON_KEY}}:{})});
 if(error){let response:{error?:string;candidates?:unknown[]}|null=null;try{response=await error.context?.json()}catch{}return NextResponse.json({error:response?.error||'Spotify bilgileri şu anda alınamadı. Tekrar deneyebilirsin.',candidates:response?.candidates||[]},{status:response?.candidates?.length?409:502});}
 return NextResponse.json(data,{headers:{'Cache-Control':'public, max-age=300'}});
 }catch{return NextResponse.json({error:'Spotify bilgileri şu anda yüklenemedi.'},{status:502})}
}
