import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/utils/supabase/server';
import {movieTrailers} from '@/utils/movieTrailers';
type Row=Record<string,any>;
const plain=(s:unknown)=>typeof s==='string'?s.replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim():'';
async function json(url:string){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'UIN/1.0 card-details'},signal:AbortSignal.timeout(15000),next:{revalidate:3600}});if(!r.ok)throw Error('Kaynak bilgileri şu anda alınamadı.');return r.json()}
async function entity(id:string){const d=await json('https://www.wikidata.org/wiki/Special:EntityData/'+id+'.json');const e=d.entities?.[id];if(!e||e.missing)throw Error('Kaynakta bu kayıt bulunamadı.');return e as Row}
const values=(e:Row,p:string)=>(e.claims?.[p]||[]).filter((c:Row)=>c.rank!=='deprecated').map((c:Row)=>c.mainsnak?.datavalue?.value).filter(Boolean);
const minutes=(v:Row|undefined)=>{if(!v?.amount)return null;const n=Number(v.amount);const unit=v.unit?.split("/").pop();const factor=unit==="Q7727"?1:unit==="Q11574"?1/60:unit==="Q25235"?60:null;return factor!=null&&Number.isFinite(n)?Math.round(n*factor)+" dk":null};
const translated=(v:string)=>({Drama:'Dram',Crime:'Suç',Thriller:'Gerilim',Comedy:'Komedi',History:'Tarih',Action:'Aksiyon',Adventure:'Macera',Romance:'Romantik',Horror:'Korku',Fantasy:'Fantastik','Science-Fiction':'Bilimkurgu',Mystery:'Gizem',English:'İngilizce',Spanish:'İspanyolca',Turkish:'Türkçe',French:'Fransızca',German:'Almanca',Ended:'Yayını sona erdi',Running:'Devam ediyor','To Be Determined':'Henüz belli değil','In Development':'Geliştirme aşamasında',Monday:'Pazartesi',Tuesday:'Salı',Wednesday:'Çarşamba',Thursday:'Perşembe',Friday:'Cuma',Saturday:'Cumartesi',Sunday:'Pazar'} as Record<string,string>)[v]||v;
const name=(e:Row)=>e.labels?.tr?.value||e.labels?.en?.value||e.sitelinks?.trwiki?.title||e.sitelinks?.enwiki?.title||e.id;
export async function GET(req:NextRequest){try{const db=await createClient();let id=req.nextUrl.searchParams.get('id')||'',provider=req.nextUrl.searchParams.get('provider')||'',kind=req.nextUrl.searchParams.get('kind')||'',title='';const targetId=req.nextUrl.searchParams.get('targetId');
if(targetId){if(!/^[0-9a-f-]{36}$/i.test(targetId))return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const p=await db.rpc('get_uin_card_profile_v60',{p_target_id:targetId});if(p.error||!p.data?.title)return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const c=await db.from('seed_catalog_items').select('external_id,external_source,item_kind,metadata').eq('canonical_target_id',targetId).eq('status','active');const item=c.data?.find(c=>['tvmaze','wikidata'].includes(c.external_source))||c.data?.[0];const meta={...(item?.metadata||{}),...(p.data.metadata||{})};const k=await db.rpc('uin_media_kind_v66',{p_target_id:targetId});kind=k.data||meta.uin_item_kind||(item?.item_kind==='video'?'series':item?.item_kind)||kind;if(!['movie','series'].includes(kind))return NextResponse.json({error:'Bu kart film veya dizi değil.'},{status:400});title=p.data.title;if(!id){id=String(meta.tvmaze_id||meta.wikidata_id||item?.external_id||'');provider=meta.tvmaze_id?'tvmaze':meta.wikidata_id?'wikidata':item?.external_source||'';}}
if(!['movie','series'].includes(kind))return NextResponse.json({error:'Film veya dizi seç.'},{status:400});
if(provider==='wikidata'&&/^Q[1-9]\d*$/.test(id)&&kind==='series'){const e=await entity(id);const tv=values(e,'P8600')[0];if(tv&&/^\d+$/.test(String(tv))){id=String(tv);provider='tvmaze'}else{id='';provider='';title=title||name(e)}}
if(kind==='series'&&(provider!=='tvmaze'||!/^\d{1,9}$/.test(id))){if(!title)throw Error('Dizi kaynağı bulunamadı.');const rows=await json('https://api.tvmaze.com/search/shows?q='+encodeURIComponent(title));const exact=rows.filter((r:Row)=>plain(r.show?.name).toLocaleLowerCase('tr-TR')===title.toLocaleLowerCase('tr-TR'));if(exact.length!==1)return NextResponse.json({error:'Dizi adının kaynak eşleşmesi kesin değil. Aşağıdan doğru yapımı seç.',candidates:rows.slice(0,10).map((r:Row)=>({id:String(r.show.id),provider:'tvmaze',title:r.show.name,year:r.show.premiered?.slice(0,4)}))},{status:409});id=String(exact[0].show.id);provider='tvmaze'}
if(kind==='series'){const [s,seasons,crew]=await Promise.all([json('https://api.tvmaze.com/shows/'+id+'?embed[]=cast&embed[]=episodes'),json('https://api.tvmaze.com/shows/'+id+'/seasons'),json('https://api.tvmaze.com/shows/'+id+'/crew').catch(()=>[])]);const network=s.network||s.webChannel;return NextResponse.json({title:s.name,kind,source:'TVmaze',sourceUrl:s.url,image:s.image?.original||s.image?.medium,summary:plain(s.summary),facts:[['Türler',(s.genres||[]).map(translated).join(' · ')],['İlk yayın',s.premiered],['Son yayın',s.ended],['Durum',translated(s.status)],['Dil',translated(s.language)],['Bölüm süresi',s.runtime||s.averageRuntime?(s.runtime||s.averageRuntime)+' dk':null],['Kanal / platform',network?.name],['Ülke',network?.country?.name],['Kaynak puanı',s.rating?.average!=null?s.rating.average+'/10':null],['Yayın düzeni',(s.schedule?.days||[]).map(translated).join(', ')+(s.schedule?.time?' · '+s.schedule.time:'')]].filter(r=>r[1]),cast:(s._embedded?.cast||[]).map((c:Row)=>({name:c.person.name,role:c.character?.name,url:c.person.url,image:c.person.image?.medium})),crew:crew.map((c:Row)=>({name:c.person?.name,role:c.type,url:c.person?.url})),seasons:seasons.map((x:Row)=>({number:x.number,name:x.name,start:x.premiereDate,end:x.endDate,summary:plain(x.summary),episodes:(s._embedded?.episodes||[]).filter((e:Row)=>e.season===x.number).map((e:Row)=>({number:e.number,name:e.name,date:e.airdate,runtime:e.runtime,summary:plain(e.summary),url:e.url}))})),links:[{label:'Resmî site',url:s.officialSite},s.externals?.imdb?{label:'IMDb',url:'https://www.imdb.com/title/'+s.externals.imdb+'/'}:null].filter(x=>x?.url)});}
if(provider!=='wikidata'||!/^Q[1-9]\d*$/.test(id)){if(!title)throw Error('Filmin kaynak kaydı bulunamadı.');const d=await json('https://www.wikidata.org/w/api.php?action=wbsearchentities&language=en&uselang=tr&format=json&limit=20&search='+encodeURIComponent(title));const rows=(d.search||[]).filter((r:Row)=>/film|movie|sinema/i.test(r.description||''));const exact=rows.filter((r:Row)=>r.label?.toLocaleLowerCase('tr-TR')===title.toLocaleLowerCase('tr-TR'));if(exact.length!==1)return NextResponse.json({error:'Filmin kaynak eşleşmesi kesin değil. Doğru yapımı seç.',candidates:rows.map((r:Row)=>({id:r.id,provider:'wikidata',title:r.label,year:r.description}))},{status:409});id=exact[0].id;provider='wikidata'}
const e=await entity(id);const props=['P57','P58','P162','P161','P136','P495','P364','P86','P272','P179'];const ids=[...new Set(props.flatMap(p=>values(e,p).map((v:Row)=>v.id).filter(Boolean)))].slice(0,150);const labels:Row={};for(let off=0;off<ids.length;off+=50){const d=await json('https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&props=labels%7Csitelinks&sitefilter=trwiki%7Cenwiki&languages=tr%7Cen&ids='+ids.slice(off,off+50).join('|'));Object.assign(labels,d.entities||{})}const names=(p:string)=>values(e,p).map((v:Row)=>labels[v.id]?name(labels[v.id]):v.id).join(' · ');const sitelink=e.sitelinks?.trwiki||e.sitelinks?.enwiki;let summary='';if(sitelink){const lang=e.sitelinks?.trwiki?'tr':'en';const d=await json('https://'+lang+'.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(sitelink.title)).catch(()=>null);summary=plain(d?.extract)}
const trailers=await movieTrailers(e,json);
const imdb=values(e,'P345')[0],official=values(e,'P856')[0],pic=values(e,'P18')[0];const dates=[...new Set(values(e,'P577').map((v:Row)=>v.time?.replace(/^\+/,'').slice(0,10).replace(/-00-00$/,'').replace(/-00$/,'')))].filter(Boolean);return NextResponse.json({title:name(e),kind,trailers,source:'Wikidata / Wikipedia',sourceUrl:sitelink?.url||'https://www.wikidata.org/wiki/'+id,image:pic?'https://commons.wikimedia.org/wiki/Special:FilePath/'+encodeURIComponent(pic)+'?width=900':null,summary:summary||e.descriptions?.tr?.value||e.descriptions?.en?.value||'',facts:[['Yönetmen',names('P57')],['Senaryo',names('P58')],['Yapımcı',names('P162')],['Türler',names('P136')],['Yayın tarihleri',dates.join(' · ')],['Süre',minutes(values(e,'P2047')[0])],['Ülke',names('P495')],['Dil',names('P364')],['Müzik',names('P86')],['Yapım şirketi',names('P272')],['Seri',names('P179')]].filter(r=>r[1]),cast:values(e,'P161').map((v:Row)=>({name:labels[v.id]?name(labels[v.id]):v.id,url:'https://www.wikidata.org/wiki/'+v.id})),crew:[],seasons:[],links:[{label:'Wikidata',url:'https://www.wikidata.org/wiki/'+id},imdb?{label:'IMDb',url:'https://www.imdb.com/title/'+imdb+'/'}:null,official?{label:'Resmî site',url:official}:null].filter(Boolean)});
}catch{return NextResponse.json({error:'Film / dizi detayları şu anda yüklenemedi. Tekrar deneyebilirsin.'},{status:502})}}
