import {cardDate} from "@/utils/targetLanguage";
import {viewingSummary,VIEWING_MODES,type ViewingContext} from "@/utils/clubProfile";
import {resolveUinCardWords,type Kind,type CardLabels} from "@/utils/uinCardLanguage";
export type WishPresentation={type_id:string;type_label:string;type_icon:string;base_kind:string;ui_labels?:CardLabels|null;viewing_context?:ViewingContext|null;start_date:string|null;end_date:string|null;timing_precision:string;date_options:string[];location:string|null};
export function wishWhen(p:Pick<WishPresentation,"start_date"|"end_date"|"timing_precision"|"date_options">){if(p.timing_precision==="multiple")return p.date_options?.length?p.date_options.map(cardDate).join(" · "):"Zamanım esnek";if(!p.start_date)return "Zamanım esnek";if(p.timing_precision==="year")return p.start_date.slice(0,4)+" boyunca";if(p.timing_precision==="month")return new Intl.DateTimeFormat("tr-TR",{month:"long",year:"numeric"}).format(new Date(p.start_date.slice(0,10)+"T12:00:00"));return cardDate(p.start_date)+(p.end_date&&p.end_date!==p.start_date?" – "+cardDate(p.end_date):"");}
export function wishWords(p:WishPresentation){return resolveUinCardWords((p.base_kind==="video"?"series":p.base_kind) as Kind,p.ui_labels)}
export function wishHow(p:WishPresentation){const c=p.viewing_context;if(!c)return "";if(p.base_kind==="club")return VIEWING_MODES[c.mode as keyof typeof VIEWING_MODES]||"Henüz karar vermedim";return viewingSummary(c);}
export function wishBadge(p:WishPresentation){return p.type_label+(p.base_kind==="club"&&p.viewing_context?.sport?" · Branş: "+p.viewing_context.sport:"");}
export default function PersonalWishSummary({presentation:p,wantLabel,notes}:{presentation:WishPresentation;wantLabel?:string;notes?:string|null}){const how=wishHow(p);return <div className="space-y-3"><p className="text-base font-black leading-6 text-emerald-800">{wantLabel||wishWords(p).want}</p><dl className="space-y-2 text-sm">{p.base_kind==="club"&&<div><dt className="text-xs text-slate-500">Branş</dt><dd className="font-bold text-slate-900">{p.viewing_context?.sport||"Henüz branş seçmedim"}</dd></div>}{how&&<div><dt className="text-xs text-slate-500">Nasıl?</dt><dd className="font-semibold text-slate-900">{how}</dd></div>}{p.base_kind==="club"&&<div><dt className="text-xs text-slate-500">Hangi maç?</dt><dd className="font-semibold text-slate-900">{p.viewing_context?.match||"Henüz maç seçmedim"}</dd></div>}<div className="rounded-xl bg-emerald-50 px-3 py-2"><dt className="text-xs text-emerald-700">📅 Ne zaman?</dt><dd className="mt-1 font-semibold text-emerald-900">{wishWhen(p)}</dd></div><div><dt className="text-xs text-slate-500">📍 Nerede?</dt><dd className="font-semibold text-slate-900">{p.location||"Konum belirlemedim"}</dd></div></dl>{notes&&<p className="whitespace-pre-line text-sm text-slate-600">{notes}</p>}</div>}
