import Link from "next/link";
import { notFound } from "next/navigation";
import AppNavigation from "@/components/navigation/AppNavigation";
import SportsBreadcrumbs from "@/components/sports/SportsBreadcrumbs";
import { createClient } from "@/utils/supabase/server";
import { metric, type SportLeagueCard } from "@/utils/sportsCatalogue";

export const dynamic="force-dynamic";
export default async function SportLeaguesPage({params}:{params:Promise<{sportSlug:string}>}){
  const {sportSlug}=await params;const supabase=await createClient();const {data,error}=await supabase.rpc("get_sport_leagues_v47",{p_sport_slug:sportSlug});const items=(data??[]) as SportLeagueCard[];const first=items[0];if(!error&&!first)notFound();
  return <main className="min-h-screen bg-gray-50 px-4 py-6 md:px-6"><div className="relative z-50 mx-auto mb-8 max-w-[1320px]"><AppNavigation/></div><div className="mx-auto max-w-[1320px]"><header className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm md:p-8"><SportsBreadcrumbs items={[{label:"Sporu Yerinde İzle",href:"/sports"},{label:first?`${first.sport_icon} ${first.sport_name}`:sportSlug}]}/><p className="mt-7 text-xs font-black uppercase tracking-[.18em] text-emerald-700">{first?.federation_short_name||"SPOR FEDERASYONU"}</p><h1 className="mt-2 text-3xl font-black">{first?.federation_name||"Türkiye ligleri"}</h1><p className="mt-2 text-sm text-gray-500">Aktif ligi seçerek bu sezon mücadele eden takımları görebilirsin.</p></header>{error?<p className="mt-6 rounded-2xl border border-red-200 bg-white p-6 text-red-700">Ligler şu anda yüklenemedi.</p>:<section className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><Link key={item.id} href={`/sports/${encodeURIComponent(item.sport_slug)}/${encodeURIComponent(item.slug)}`} className="group rounded-3xl border border-gray-200 bg-white p-6 shadow-sm transition hover:border-emerald-300 hover:shadow-md">{item.logo_url&&<img src={item.logo_url} alt="" className="h-16 w-16 object-contain"/>}<p className="text-xs font-black uppercase tracking-wide text-emerald-700">{item.sport_icon} {item.sport_name} · {item.federation_short_name}</p><h2 className="mt-3 text-2xl font-black group-hover:text-emerald-700">{item.name}</h2>{item.season_label&&<p className="mt-1 text-sm font-semibold text-gray-500">{item.season_label} sezonu</p>}<div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs font-black text-emerald-700">Takımlar</p><p className="mt-1 text-2xl font-black">{metric(item.team_count)}</p></div><div className="rounded-2xl bg-violet-50 p-4"><p className="text-xs font-black text-violet-700">Etkinlikler</p><p className="mt-1 text-2xl font-black">{metric(item.event_count)}</p></div></div></Link>)}</section>}</div></main>;
}
