"use client";

import Link from "next/link";
import { type ReactNode, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import AdminRemoveIntentButton from "@/components/admin/AdminRemoveIntentButton";
import CommonPersonalIntentForm from "@/components/intentions/CommonPersonalIntentForm";
import CommonTargetEventForm from "@/components/intentions/CommonTargetEventForm";
import CollaborationProposal from "@/components/seeds/CollaborationProposal";

type Participant={user_id:string;full_name:string;username:string|null;avatar_url:string|null;role:"owner"|"participant"};
type PersonalIntent={id:string;seed_id?:string|null;source_kind?:string|null;user_id:string;full_name:string;username:string|null;avatar_url:string|null;start_date:string|null;end_date:string|null;notes:string|null;location:string|null};
type EventIntent={intent_id:string;plan_id:string|null;subtitle:string|null;start_date:string;end_date:string;visibility:string;location:string;meeting_point?:string|null;activity_location?:string|null;owner_user_id?:string|null;owner_name:string;owner_username:string|null;owner_avatar_url:string|null;participant_count:number|string;participants?:Participant[];max_participants:number|null;viewer_is_owner?:boolean;viewer_is_member:boolean;status?:string|null;plan_status?:string|null;event_state?:"active"|"completed"|"expired"|"cancelled"};
type Sort="date_desc"|"date_asc"|"location";
const PAGE_SIZE=10;

function formatDate(value:string|null){if(!value)return"Tarih esnek";return new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00`))}
function dateRange(start:string|null,end:string|null){if(!start)return"Tarih esnek";if(!end||end===start)return formatDate(start);return`${formatDate(start)} – ${formatDate(end)}`}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toLocaleUpperCase("tr-TR")||"?"}
function ProfileAvatar({name,username,avatar,size="md"}:{name:string;username:string|null;avatar:string|null;size?:"sm"|"md"}){const cls=size==="sm"?"h-8 w-8 text-[10px]":"h-11 w-11 text-xs";const visual=avatar?<img src={avatar} alt="" className={`${cls} rounded-full object-cover`}/>:<span className={`${cls} grid place-items-center rounded-full bg-gray-100 font-black text-gray-600`}>{initials(name)}</span>;return username?<Link href={`/u/${encodeURIComponent(username)}`} title={name}>{visual}</Link>:visual}
function ParticipantStack({people}:{people:Participant[]}){const visible=people.slice(0,4),remaining=people.length-visible.length;if(!people.length)return <span className="text-sm text-gray-500">Katılımcılar bekleniyor</span>;return <div className="flex items-center gap-2"><div className="flex -space-x-2">{visible.map(person=><span key={person.user_id} className="rounded-full border-2 border-white" title={person.full_name}><ProfileAvatar name={person.full_name} username={person.username} avatar={person.avatar_url} size="sm"/></span>)}</div>{remaining>0&&<span className="text-xs font-black">+{remaining}</span>}<span className="text-xs font-bold text-gray-500">{people.length} kişi</span></div>}
function compare(a:{start_date:string|null;location?:string|null},b:{start_date:string|null;location?:string|null},sort:Sort){if(sort==="location")return(a.location||"").localeCompare(b.location||"","tr");const av=a.start_date||"0000-00-00",bv=b.start_date||"0000-00-00";return sort==="date_desc"?bv.localeCompare(av):av.localeCompare(bv)}
function stateOf(event:EventIntent){if(event.event_state)return event.event_state;if(event.status==="completed"||event.plan_status==="completed")return"completed";if(["cancelled","canceled"].includes(event.status||"")||["cancelled","canceled"].includes(event.plan_status||""))return"cancelled";const today=new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Istanbul"});return(event.end_date||event.start_date)<today?"expired":"active"}
function stateLabel(state:ReturnType<typeof stateOf>){return state==="completed"?"Tamamlandı":state==="expired"?"Tarihi geçti":state==="cancelled"?"İptal edildi":"Aktif"}
function Pagination({page,total,onChange}:{page:number;total:number;onChange:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));if(pages<=1)return null;return <div className="flex items-center justify-center gap-2 border-t border-gray-100 p-4"><button type="button" disabled={page===1} onClick={()=>onChange(page-1)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-30">← Önceki</button><span className="px-2 text-xs font-black">{page} / {pages}</span><button type="button" disabled={page===pages} onClick={()=>onChange(page+1)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-30">Sonraki →</button></div>}
function Filters({location,setLocation,date,setDate,sort,setSort,onReset}:{location:string;setLocation:(v:string)=>void;date:string;setDate:(v:string)=>void;sort:Sort;setSort:(v:Sort)=>void;onReset:()=>void}){return <div className="grid gap-2 border-b border-gray-100 bg-gray-50 p-3 sm:grid-cols-[1fr_1fr_1fr_auto]"><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Konuma göre filtrele" className="rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm"/><label className="flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-3 text-xs font-bold text-gray-500"><span>Tarihten sonra</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="min-w-0 flex-1 py-2 text-sm text-gray-900"/></label><select value={sort} onChange={e=>setSort(e.target.value as Sort)} className="rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm font-bold"><option value="date_desc">Yeniden eskiye</option><option value="date_asc">Eskiden yeniye</option><option value="location">Konuma göre</option></select><button type="button" onClick={onReset} className="rounded-xl border border-gray-200 bg-white px-3 py-2 text-xs font-bold">Temizle</button></div>}
function SectionHead({title,count,tone,action}:{title:string;count:number;tone:"violet"|"emerald";action?:ReactNode}){return <div className="flex flex-wrap items-center justify-between gap-3 p-4 md:p-6"><h2 className="text-xl font-black md:text-2xl">{title}</h2><div className="flex items-center gap-3">{action}<span className={`rounded-full px-3 py-2 text-sm font-black ${tone==="violet"?"bg-violet-100 text-violet-800":"bg-emerald-100 text-emerald-800"}`}>{count}</span></div></div>}
function Modal({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-[28px] bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b bg-white p-5 md:p-7"><div><h2 className="text-2xl font-black">{title}</h2><p className="mt-1 text-sm text-gray-500">{subtitle}</p></div><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full border text-xl">×</button></header><div className="p-5 md:p-7">{children}</div></section></div>}

export default function CommonTargetUpcomingList({targetId,targetTitle,targetAction,wantHeading,wantActionLabel,viewerId,initialActivityId="",isSport,personalIntents,events,isAdmin}:{targetId:string;targetTitle:string;targetAction:string;wantHeading:string;wantActionLabel:string;viewerId:string|null;initialActivityId?:string|null;isSport:boolean;personalIntents:PersonalIntent[];events:EventIntent[];isAdmin:boolean}){
  const router=useRouter();const [eventPage,setEventPage]=useState(1);const [peopleLocation,setPeopleLocation]=useState(""),[peopleDate,setPeopleDate]=useState(""),[peopleSort,setPeopleSort]=useState<Sort>("date_desc"),[peoplePage,setPeoplePage]=useState(1);const [wantOpen,setWantOpen]=useState(false);const [eventOpen,setEventOpen]=useState(false);const [eventToEdit,setEventToEdit]=useState<EventIntent|null>(null);
  const ownWant=personalIntents.find(item=>item.user_id===viewerId)||null;const ownEvent=events.find(item=>item.viewer_is_owner||item.owner_user_id===viewerId)||null;
  const filteredEvents=useMemo(()=>events.filter(event=>stateOf(event)==="active").sort((a,b)=>{const own=Number(Boolean(b.viewer_is_owner))-Number(Boolean(a.viewer_is_owner));return own||compare(a,b,"date_asc")}),[events]);
  const historyEvents=useMemo(()=>events.filter(event=>stateOf(event)!=="active").sort((a,b)=>compare(a,b,"date_desc")),[events]);
  const filteredPeople=useMemo(()=>personalIntents.filter(item=>(item.location||"").toLocaleLowerCase("tr-TR").includes(peopleLocation.trim().toLocaleLowerCase("tr-TR"))&&(!peopleDate||!item.end_date||item.end_date>=peopleDate)).sort((a,b)=>{const own=Number(b.user_id===viewerId)-Number(a.user_id===viewerId);return own||compare(a,b,peopleSort)}),[personalIntents,peopleLocation,peopleDate,peopleSort,viewerId]);
  const eventRows=filteredEvents.slice((eventPage-1)*PAGE_SIZE,eventPage*PAGE_SIZE),peopleRows=filteredPeople.slice((peoplePage-1)*PAGE_SIZE,peoplePage*PAGE_SIZE);
  const signInHref=`/?returnTo=${encodeURIComponent(`/intentions/${targetId}`)}`;
  const eventAction=viewerId?<button type="button" onClick={()=>{setEventToEdit(ownEvent);setEventOpen(true)}} className="rounded-xl bg-violet-700 px-4 py-2.5 text-sm font-black text-white">{ownEvent?"Düzenle":"Etkinlik oluştur"}</button>:<Link href={signInHref} className="rounded-xl bg-violet-700 px-4 py-2.5 text-sm font-black text-white">Giriş yap</Link>;
  const wantAction=viewerId?<button type="button" onClick={()=>setWantOpen(true)} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">{ownWant?"Düzenle":wantActionLabel}</button>:<Link href={signInHref} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Giriş yap</Link>;
  return <section id="social-intents" className="mt-8 scroll-mt-6 space-y-6">
    <div className="overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm"><SectionHead title="Etkinlikler" count={filteredEvents.length} tone="violet" action={eventAction}/><div className="divide-y divide-gray-100">{eventRows.length?eventRows.map(event=>{const href=`/activities/${encodeURIComponent(event.plan_id||event.intent_id)}`;const participants=(event.participants||[]).filter(person=>person.role!=="owner");return <article key={event.intent_id} className="p-4 hover:bg-gray-50/80 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-lg font-black">{event.subtitle||`${targetTitle} etkinliği`}</p><p className="mt-1 text-sm font-bold text-gray-600">{dateRange(event.start_date,event.end_date)}</p></div><div className="flex items-center gap-2">{isAdmin&&<AdminRemoveIntentButton intentId={event.intent_id}/>} {event.viewer_is_owner?<button type="button" onClick={()=>{setEventToEdit(event);setEventOpen(true)}} className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-sm font-black text-violet-800">Düzenle</button>:<Link href={href} className={`rounded-xl px-4 py-3 text-sm font-black ${event.viewer_is_member?"border border-violet-200 bg-violet-50 text-violet-800":"bg-violet-700 text-white"}`}>{event.viewer_is_member?"Katılıyorsun · Aç":"Etkinliği aç"}</Link>}</div></div><div className="mt-5 grid gap-4 rounded-2xl bg-gray-50 p-4 sm:grid-cols-2 lg:grid-cols-3"><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Düzenleyen</p><div className="mt-2 flex items-center gap-2"><ProfileAvatar name={event.owner_name} username={event.owner_username} avatar={event.owner_avatar_url} size="sm"/><span className="truncate text-sm font-black">{event.owner_name}</span></div></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Katılımcılar</p><div className="mt-2"><ParticipantStack people={participants}/></div></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Konu bağlamı</p><p className="mt-2 text-sm font-black">{targetTitle}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Buluşma noktası</p><p className="mt-2 text-sm font-bold">{event.meeting_point||"Henüz netleşmedi"}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Etkinlik alanı</p><p className="mt-2 text-sm font-bold">{event.activity_location||event.location||"Henüz netleşmedi"}</p></div></div></article>}):<Empty text="Henüz yaklaşan etkinlik yok."/>}</div><Pagination page={eventPage} total={filteredEvents.length} onChange={setEventPage}/></div>
    {historyEvents.length>0&&<div className="overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm"><SectionHead title="Tamamlanan ve geçmiş etkinlikler" count={historyEvents.length} tone="violet"/><div className="divide-y divide-gray-100">{historyEvents.map(event=>{const state=stateOf(event);const href=`/activities/${encodeURIComponent(event.plan_id||event.intent_id)}`;return <article key={event.intent_id} className="flex flex-wrap items-center justify-between gap-4 bg-gray-50/70 p-4 opacity-75 md:px-6"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black">{event.subtitle||`${targetTitle} etkinliği`}</p><span className="rounded-full bg-gray-200 px-2 py-1 text-[10px] font-black text-gray-700">{stateLabel(state)}</span></div><p className="mt-1 text-sm text-gray-500">{dateRange(event.start_date,event.end_date)} · {event.location||"Konum belirtilmedi"}</p></div>{state==="completed"?<Link href={href} className="rounded-xl border border-gray-300 bg-white px-4 py-2 text-sm font-black text-gray-700">Deneyimi gör</Link>:<span className="text-xs font-bold text-gray-500">Pasif</span>}</article>})}</div></div>}
    <div className="overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm"><SectionHead title={wantHeading} count={filteredPeople.length} tone="emerald" action={wantAction}/><Filters location={peopleLocation} setLocation={v=>{setPeopleLocation(v);setPeoplePage(1)}} date={peopleDate} setDate={v=>{setPeopleDate(v);setPeoplePage(1)}} sort={peopleSort} setSort={v=>{setPeopleSort(v);setPeoplePage(1)}} onReset={()=>{setPeopleLocation("");setPeopleDate("");setPeopleSort("date_desc");setPeoplePage(1)}}/><div className="divide-y divide-gray-100">{peopleRows.length?peopleRows.map(item=>{const own=item.user_id===viewerId;return <article key={item.id} className={`grid gap-4 p-4 md:grid-cols-[minmax(180px,1.15fr)_1fr_1fr_1.2fr_auto] md:items-center md:px-6 ${own?"bg-emerald-50/60":"hover:bg-gray-50/80"}`}><div className="flex min-w-0 items-center gap-3"><ProfileAvatar name={item.full_name} username={item.username} avatar={item.avatar_url}/><div className="min-w-0"><p className="truncate font-black">{item.full_name}</p><p className="text-xs text-gray-400">{own?"Sen · listenin başında":wantActionLabel}</p></div></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Müsait olduğu tarih</p><p className="mt-1 text-sm font-bold">{dateRange(item.start_date,item.end_date)}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Konum</p><p className="mt-1 text-sm font-bold">{item.location||"Henüz netleşmedi"}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-gray-400">Not</p><p className="mt-1 text-sm font-bold">{item.notes||"Henüz belirtmedi"}</p></div>{own?<button type="button" onClick={()=>setWantOpen(true)} className="rounded-xl border border-emerald-200 bg-white px-4 py-3 text-sm font-black text-emerald-800">Düzenle</button>:item.seed_id?<CollaborationProposal seedId={item.seed_id} name={item.full_name} targetId={targetId}/>:<span className="max-w-44 text-xs font-semibold text-gray-500">Bu niyet için öneri henüz kullanılamıyor.</span>}</article>}):<Empty text="Henüz bu kart için aktif kişisel niyet yok."/>}</div><Pagination page={peoplePage} total={filteredPeople.length} onChange={setPeoplePage}/></div>
    {wantOpen&&<Modal title={ownWant?"İsteğini düzenle":wantActionLabel} subtitle={`${targetTitle} UIN Kartına bağlı kişisel isteğin`} onClose={()=>setWantOpen(false)}><CommonPersonalIntentForm targetId={targetId} isSport={isSport} embedded noteLabel="Notun" notePlaceholder="Uygun olduğun saatleri veya bu konudaki beklentini yaz…" saveLabel={ownWant?"Değişiklikleri kaydet":"İsteyenlere ekle"} onSaved={()=>{setWantOpen(false);router.refresh()}}/></Modal>}
    {eventOpen&&<Modal title={eventToEdit?"Etkinliği düzenle":"Etkinlik oluştur"} subtitle="Konu seçmeden, bu kartın bağlamında planla" onClose={()=>setEventOpen(false)}><CommonTargetEventForm targetId={targetId} targetTitle={targetTitle} targetAction={targetAction} initialActivityId={initialActivityId||""} existing={eventToEdit} onSaved={()=>{setEventOpen(false);setEventToEdit(null);router.refresh()}}/></Modal>}
  </section>;
}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-sm font-semibold text-gray-500">{text}</div>}
