import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/utils/supabase/server';
import {bookPlain,bookUrl} from '@/utils/bookDetails';
const cache=new Map<string,{expires:number;data:any}>();
export async function GET(req:NextRequest){try{const db=await createClient();let id=req.nextUrl.searchParams.get('id')||'',query='';const targetId=req.nextUrl.searchParams.get('targetId');let fallback:any=null;
 if(id&&!/^\d{1,10}$/.test(id))return NextResponse.json({error:'Geçersiz oyun kaydı.'},{status:400});
 if(targetId){if(!/^[0-9a-f-]{36}$/i.test(targetId))return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const p=await db.rpc('get_uin_card_profile_v60',{p_target_id:targetId});if(p.error||!p.data?.title)return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const c=await db.from('seed_catalog_items').select('external_id,external_source,item_kind,metadata').eq('canonical_target_id',targetId).eq('status','active');const item=c.data?.find(x=>x.item_kind==='game');if(!item)return NextResponse.json({error:'Bu kart bir oyun değil.'},{status:400});query=p.data.title;const meta={...(item.metadata||{}),...(p.data.metadata||{})};if(!id){const candidate=String(meta.igdb_id||(item.external_source==='igdb'?item.external_id:'')||'');if(/^\d{1,10}$/.test(candidate))id=candidate}fallback={title:query,coverUrl:p.data.cover_url,sourceUrl:meta.igdb_url,metadata:meta};}
 if(!id&&!query)return NextResponse.json({error:'Kaynakta bir oyun seç.'},{status:400});
 const key=id||query;let item:any;const hit=cache.get(key);if(hit&&hit.expires>Date.now())item=hit.data;else{const r=await db.functions.invoke('uin-igdb-search',{body:{gameId:id||null,query},...(process.env.SUPABASE_FUNCTION_ANON_KEY?{headers:{Authorization:'Bearer '+process.env.SUPABASE_FUNCTION_ANON_KEY}}:{})});if(!r.error&&!r.data?.error){const items=r.data?.items||[];const matching=id?items.filter((x:any)=>x.externalId===id):items.filter((x:any)=>x.title.toLocaleLowerCase('tr-TR')===query.toLocaleLowerCase('tr-TR'));if(matching.length===1)item=matching[0];else return NextResponse.json({error:'Doğru oyun sürümünü seç.',candidates:items.map((x:any)=>({id:x.externalId,title:x.title,subtitle:x.subtitle}))},{status:409});if(cache.size>=100)cache.delete(cache.keys().next().value!);cache.set(key,{expires:Date.now()+3600000,data:item})}else if(fallback)item=fallback;else throw Error('Oyun kaynağı alınamadı.')}
 const m=item.metadata||{};let steam:any=null;try{const url=new URL(m.steam_url);const app=url.hostname==='store.steampowered.com'?url.pathname.match(/^\/app\/(\d{1,10})(?:\/|$)/)?.[1]:null;if(app){const r=await fetch('https://store.steampowered.com/api/appdetails?appids='+app+'&l=turkish&cc=tr',{signal:AbortSignal.timeout(8000),next:{revalidate:3600}});if(r.ok){const d=await r.json();if(d[app]?.success&&d[app]?.data?.type==='game')steam=d[app].data;}}}catch{}
 const names=(x:any)=>Array.isArray(x)?x.filter((v:any)=>typeof v==='string').join(' · '):'';
 const facts=[['Platformlar',names(m.platforms)],['Türler',steam?.genres?.map((x:any)=>x.description).join(' · ')||names(m.genres)],['Geliştirici',names(m.developers)],['Yayıncı',names(m.publishers)],['Çıkış tarihi',m.release_date],['Oyun modları',names(m.game_modes)],['IGDB puanı',typeof m.rating==='number'?Math.round(m.rating)+'/100'+(m.rating_count?' · '+m.rating_count+' değerlendirme':''):'']].filter(x=>x[1]);
 const screenshots=[...new Set([...(steam?.screenshots||[]).map((x:any)=>x.path_full),...(m.screenshots||[])])].filter((x:any)=>bookUrl(x)).slice(0,12);
 return NextResponse.json({title:item.title,summary:bookPlain(steam?.detailed_description||steam?.short_description||m.description),storyline:bookPlain(m.storyline),image:bookUrl(steam?.header_image||item.coverUrl),facts,screenshots,videos:(m.videos||[]).filter((v:any)=>/^[A-Za-z0-9_-]{11}$/.test(v.videoId||'')).slice(0,8),requirements:steam?[['Windows',bookPlain(steam.pc_requirements?.minimum)],['Mac',bookPlain(steam.mac_requirements?.minimum)],['Linux',bookPlain(steam.linux_requirements?.minimum)]].filter(x=>x[1]):[],links:[{label:'IGDB’de görüntüle',url:bookUrl(item.sourceUrl||m.igdb_url)},{label:steam?.movies?.length?'Steam’de oyun ve videolar':'Steam’de görüntüle',url:bookUrl(m.steam_url)}].filter(x=>x.url),source:steam?'IGDB / Steam':'IGDB'});
 }catch{return NextResponse.json({error:'Oyun detayları şu anda yüklenemedi. Tekrar deneyebilirsin.'},{status:502})}}
