"use client";
import {useEffect,useMemo,useState} from "react";

type Country={country_code:string;country_name:string;target_id:string;city_count:number};
export type PlaceBrowseNode={target_id:string;title:string;scope:string;parent_target_id:string|null;source_key:string;child_count:number};
type Card=Record<string,unknown>&{canonical_target_id:string;title:string};
type Payload={countries:Country[];nodes:PlaceBrowseNode[];cards:Card[];error?:string};
export type PlaceBrowseSelection={countryCode:string;cityTargetId:string;districtTargetId:string};

export default function PlaceHierarchyBrowser({onData}:{onData:(cards:Card[],nodes:PlaceBrowseNode[],selection:PlaceBrowseSelection)=>void}){
 const[countries,setCountries]=useState<Country[]>([]),[cities,setCities]=useState<PlaceBrowseNode[]>([]),[cityLevel,setCityLevel]=useState<PlaceBrowseNode[]>([]),[country,setCountry]=useState("TR"),[city,setCity]=useState(""),[district,setDistrict]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState("");
 async function request(code:string,cityId="",districtId="",includeCountries=false,includeCards=true){const params=new URLSearchParams({country:code});if(cityId)params.set("city",cityId);if(districtId)params.set("district",districtId);if(includeCountries)params.set("include_countries","1");if(!includeCards)params.set("include_cards","0");const response=await fetch(`/api/places/hierarchy?${params}`,{cache:"no-store"});const body=await response.json() as Payload;if(!response.ok)throw new Error(body.error||"Yer hiyerarşisi yüklenemedi.");if(body.countries?.length)setCountries(body.countries);return body}
 async function loadCountry(code:string){setBusy(true);setError("");try{const top=await request(code,"","",true,code!=="TR");setCountry(code);setCities(top.nodes);setDistrict("");const defaultCity=code==="TR"?top.nodes.find(node=>node.title.toLocaleLowerCase("tr-TR")==="istanbul"||node.title.toLocaleLowerCase("tr-TR")==="i̇stanbul")?.target_id||"":"";setCity(defaultCity);if(defaultCity){const level=await request(code,defaultCity);setCityLevel(level.nodes);onData(level.cards,level.nodes,{countryCode:code,cityTargetId:defaultCity,districtTargetId:""})}else{setCityLevel([]);onData(top.cards,top.nodes,{countryCode:code,cityTargetId:"",districtTargetId:""})}}catch(cause){setError(cause instanceof Error?cause.message:"Yerler yüklenemedi.")}finally{setBusy(false)}}
 async function chooseCity(targetId:string){setCity(targetId);setDistrict("");setBusy(true);setError("");try{if(!targetId){setCityLevel([]);const top=await request(country);onData(top.cards,top.nodes,{countryCode:country,cityTargetId:"",districtTargetId:""});return}const level=await request(country,targetId);setCityLevel(level.nodes);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:targetId,districtTargetId:""})}catch(cause){setError(cause instanceof Error?cause.message:"Şehir yüklenemedi.")}finally{setBusy(false)}}
 async function chooseDistrict(targetId:string){setDistrict(targetId);setBusy(true);setError("");try{if(!targetId){const level=await request(country,city);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:city,districtTargetId:""});return}const level=await request(country,city,targetId);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:city,districtTargetId:targetId})}catch(cause){setError(cause instanceof Error?cause.message:"İlçe yüklenemedi.")}finally{setBusy(false)}}
 useEffect(()=>{const listener=(event:Event)=>{const targetId=(event as CustomEvent<{targetId?:string}>).detail?.targetId;if(targetId&&cityLevel.some(node=>node.scope==="district"&&node.target_id===targetId))void chooseDistrict(targetId)};window.addEventListener("uin:place-drilldown",listener);return()=>window.removeEventListener("uin:place-drilldown",listener)});
 // İlk görünüm sabit olarak Türkiye → İstanbul'dur.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void loadCountry("TR")},[]);
 const districts=useMemo(()=>cityLevel.filter(node=>node.scope==="district"||node.scope==="İlçe"),[cityLevel]);
 return <div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4"><div className="mb-3 flex items-center justify-between"><div><p className="font-black text-slate-950">Yer seçimi</p><p className="text-xs font-semibold text-slate-500">Ülke → il/şehir → ilçe → yer</p></div>{busy?<span className="text-xs font-bold text-emerald-700">Yükleniyor…</span>:null}</div><div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold text-slate-500">Ülke<select value={country} onChange={event=>void loadCountry(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900">{countries.map(item=><option key={item.country_code} value={item.country_code}>{item.country_name} · {item.city_count}</option>)}</select></label><label className="text-xs font-bold text-slate-500">İl / şehir<select value={city} onChange={event=>void chooseCity(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900"><option value="">{country==="TR"?"81 ili göster":"Şehirleri göster"}</option>{cities.map(node=><option key={node.target_id} value={node.target_id}>{node.title}</option>)}</select></label>{city&&districts.length?<label className="text-xs font-bold text-slate-500">İlçe<select value={district} onChange={event=>void chooseDistrict(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900"><option value="">İstanbul ve ilçeleri</option>{districts.map(node=><option key={node.target_id} value={node.target_id}>{node.title}{node.child_count?` · ${node.child_count} yer`:""}</option>)}</select></label>:null}</div>{error?<p className="mt-3 text-sm font-bold text-red-700">{error}</p>:null}</div>
}
