"use client";
import {useEffect,useMemo,useState} from "react";

type Country={country_code:string;country_name:string;target_id:string;city_count:number;population:number};
export type PlaceBrowseNode={target_id:string;title:string;scope:string;parent_target_id:string|null;source_key:string;child_count:number};
type Card=Record<string,unknown>&{canonical_target_id:string;title:string};
type Payload={countries:Country[];nodes:PlaceBrowseNode[];cards:Card[];error?:string};
export type PlaceBrowseSelection={countryCode:string;cityTargetId:string;districtTargetId:string};
const COUNTRY_PAGE_SIZE=20;
const populationLabel=(value:number)=>value>0?new Intl.NumberFormat("tr-TR",{notation:"compact",maximumFractionDigits:1}).format(value):"Bilinmiyor";
const countryFlag=(code:string)=>/^[A-Z]{2}$/.test(code)?String.fromCodePoint(...code.split("").map(letter=>127397+letter.charCodeAt(0))):"🌍";

export default function PlaceHierarchyBrowser({onData}:{onData:(cards:Card[],nodes:PlaceBrowseNode[],selection:PlaceBrowseSelection)=>void}){
 const[countries,setCountries]=useState<Country[]>([]),[cities,setCities]=useState<PlaceBrowseNode[]>([]),[cityLevel,setCityLevel]=useState<PlaceBrowseNode[]>([]),[country,setCountry]=useState("TR"),[city,setCity]=useState(""),[district,setDistrict]=useState(""),[cityQuery,setCityQuery]=useState(""),[showCountries,setShowCountries]=useState(false),[countryPage,setCountryPage]=useState(1),[busy,setBusy]=useState(true),[error,setError]=useState("");
 async function request(code:string,cityId="",districtId="",includeCountries=false,includeCards=true,query="",limit=500){const params=new URLSearchParams({country:code,limit:String(limit)});if(cityId)params.set("city",cityId);if(districtId)params.set("district",districtId);if(query.trim())params.set("q",query.trim());if(includeCountries)params.set("include_countries","1");if(!includeCards)params.set("include_cards","0");const response=await fetch(`/api/places/hierarchy?${params}`,{cache:"no-store"});const body=await response.json() as Payload;if(!response.ok)throw new Error(body.error||"Yer hiyerarşisi yüklenemedi.");if(body.countries?.length)setCountries(body.countries);return body}
 async function loadCountry(code:string){setBusy(true);setError("");setCityQuery("");setShowCountries(false);try{const top=await request(code,"","",true,false,"",100);setCountry(code);setCities(top.nodes);setDistrict("");const defaultCity=code==="TR"?top.nodes.find(node=>node.title.toLocaleLowerCase("tr-TR")==="istanbul"||node.title.toLocaleLowerCase("tr-TR")==="i̇stanbul")?.target_id||"":"";setCity(defaultCity);if(defaultCity){const level=await request(code,defaultCity);setCityLevel(level.nodes);onData(level.cards,level.nodes,{countryCode:code,cityTargetId:defaultCity,districtTargetId:""})}else{setCityLevel([]);onData([],top.nodes,{countryCode:code,cityTargetId:"",districtTargetId:""})}}catch(cause){setError(cause instanceof Error?cause.message:"Yerler yüklenemedi.")}finally{setBusy(false)}}
 async function searchCities(){setBusy(true);setError("");try{const top=await request(country,"","",false,false,cityQuery,100);setCities(top.nodes);setCity("");setDistrict("");setCityLevel([]);onData([],top.nodes,{countryCode:country,cityTargetId:"",districtTargetId:""});if(!top.nodes.length)setError("Bu adla bir şehir bulunamadı.")}catch(cause){setError(cause instanceof Error?cause.message:"Şehirler aranamadı.")}finally{setBusy(false)}}
 async function chooseCity(targetId:string){setCity(targetId);setDistrict("");setBusy(true);setError("");try{if(!targetId){setCityLevel([]);const top=await request(country,"","",false,country==="TR","",country==="TR"?100:100);setCities(top.nodes);onData(country==="TR"?top.cards:[],top.nodes,{countryCode:country,cityTargetId:"",districtTargetId:""});return}const level=await request(country,targetId);setCityLevel(level.nodes);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:targetId,districtTargetId:""})}catch(cause){setError(cause instanceof Error?cause.message:"Şehir yüklenemedi.")}finally{setBusy(false)}}
 async function chooseDistrict(targetId:string){setDistrict(targetId);setBusy(true);setError("");try{if(!targetId){const level=await request(country,city);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:city,districtTargetId:""});return}const level=await request(country,city,targetId);onData(level.cards,level.nodes,{countryCode:country,cityTargetId:city,districtTargetId:targetId})}catch(cause){setError(cause instanceof Error?cause.message:"İlçe yüklenemedi.")}finally{setBusy(false)}}
 useEffect(()=>{const listener=(event:Event)=>{const targetId=(event as CustomEvent<{targetId?:string}>).detail?.targetId;if(targetId&&cityLevel.some(node=>node.scope==="district"&&node.target_id===targetId))void chooseDistrict(targetId)};window.addEventListener("uin:place-drilldown",listener);return()=>window.removeEventListener("uin:place-drilldown",listener)});
 // İlk görünüm sabit olarak Türkiye → İstanbul'dur.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void loadCountry("TR")},[]);
 const districts=useMemo(()=>cityLevel.filter(node=>node.scope==="district"||node.scope==="İlçe"),[cityLevel]);
 const selectedCityName=cities.find(node=>node.target_id===city)?.title||"Seçili şehir";
 const countryPages=Math.max(1,Math.ceil(countries.length/COUNTRY_PAGE_SIZE));
 const activeCountryPage=Math.min(countryPage,countryPages);
 const visibleCountries=countries.slice((activeCountryPage-1)*COUNTRY_PAGE_SIZE,activeCountryPage*COUNTRY_PAGE_SIZE);
 return <div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4">
  <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
   <div><p className="font-black text-slate-950">Yer seçimi</p><p className="text-xs font-semibold text-slate-500">Ülke → il/şehir → ilçe → yer</p></div>
   <div className="flex items-center gap-2">
    {busy?<span className="text-xs font-bold text-emerald-700">Yükleniyor…</span>:null}
    <button type="button" onClick={()=>{setShowCountries(value=>!value);setCountryPage(1)}} className="rounded-xl border border-emerald-300 bg-white px-3 py-2 text-xs font-black text-emerald-800">🌍 Ülkeleri keşfet</button>
   </div>
  </div>
  {showCountries?<section className="mb-4 rounded-2xl border border-emerald-200 bg-white p-3">
   <div className="mb-3"><p className="font-black text-slate-950">Nüfusa göre ülkeler</p><p className="text-xs font-semibold text-slate-500">Her sayfada 20 ülke gösterilir. Bir ülkeye dokunarak şehirlerini açabilirsin.</p></div>
   <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{visibleCountries.map(item=><button type="button" key={item.country_code} onClick={()=>void loadCountry(item.country_code)} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${country===item.country_code?"border-emerald-500 bg-emerald-50":"border-slate-200 bg-white hover:border-emerald-300"}`}><span className="text-2xl" aria-hidden>{countryFlag(item.country_code)}</span><span className="min-w-0"><strong className="block truncate text-sm text-slate-950">{item.country_name}</strong><span className="block text-xs font-bold text-emerald-700">Nüfus · {populationLabel(item.population)}</span><span className="block text-[11px] font-semibold text-slate-500">{item.city_count} şehir</span></span></button>)}</div>
   <div className="mt-3 flex items-center justify-between gap-3 text-xs font-bold text-slate-600"><button type="button" disabled={activeCountryPage===1} onClick={()=>setCountryPage(page=>Math.max(1,page-1))} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">← Önceki 20</button><span className="text-center">{(activeCountryPage-1)*COUNTRY_PAGE_SIZE+1}–{Math.min(activeCountryPage*COUNTRY_PAGE_SIZE,countries.length)} / {countries.length} ülke · Sayfa {activeCountryPage}/{countryPages}</span><button type="button" disabled={activeCountryPage===countryPages} onClick={()=>setCountryPage(page=>Math.min(countryPages,page+1))} className="rounded-lg border bg-white px-3 py-2 disabled:opacity-40">Sonraki 20 →</button></div>
  </section>:null}
  {country!=="TR"?<form onSubmit={event=>{event.preventDefault();void searchCities()}} className="mb-3 flex flex-col gap-2 sm:flex-row"><input value={cityQuery} onChange={event=>setCityQuery(event.target.value)} placeholder="Şehir ara: Londra, Paris, Oslo…" className="min-w-0 flex-1 rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900"/><button type="submit" disabled={busy||cityQuery.trim().length<2} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">Şehri bul</button></form>:null}
  <div className="grid gap-3 md:grid-cols-3"><label className="text-xs font-bold text-slate-500">Ülke<select value={country} onChange={event=>void loadCountry(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900">{countries.map(item=><option key={item.country_code} value={item.country_code}>{item.country_name} · {populationLabel(item.population)} · {item.city_count} şehir</option>)}</select></label><label className="text-xs font-bold text-slate-500">İl / şehir<select value={city} onChange={event=>void chooseCity(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900"><option value="">{country==="TR"?"81 ili göster":"Şehir seç"}</option>{cities.map(node=><option key={node.target_id} value={node.target_id}>{node.title}</option>)}</select></label>{city&&districts.length?<label className="text-xs font-bold text-slate-500">İlçe<select value={district} onChange={event=>void chooseDistrict(event.target.value)} className="mt-1 block w-full rounded-xl border bg-white px-4 py-3 text-sm font-bold text-slate-900"><option value="">{selectedCityName} ve ilçeleri</option>{districts.map(node=><option key={node.target_id} value={node.target_id}>{node.title}{node.child_count?` · ${node.child_count} yer`:""}</option>)}</select></label>:null}</div>
  {country!=="TR"&&!city?<p className="mt-3 text-xs font-semibold text-emerald-900">Kartlar, bir şehir seçtiğinde yüklenir. Böylece büyük ülkelerde bekleme ve zaman aşımı oluşmaz.</p>:null}
  {error?<p className="mt-3 text-sm font-bold text-red-700">{error}</p>:null}
 </div>
}
