"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Message={role:"user"|"assistant";content:string};

export default function TopicAiAssistant({cacheKey,title,kind,context}:{cacheKey:string;title:string;kind:string;context?:string}){
  const [configured,setConfigured]=useState<boolean|null>(null),[tier,setTier]=useState<"standard"|"gold">("standard"),[messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[errorCode,setErrorCode]=useState("");const started=useRef(false);const storageKey=`uin-ai:${cacheKey}`;
  async function ask(text:string,history:Message[]=messages){setBusy(true);setError("");setErrorCode("");try{const response=await fetch("/api/ideas/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,kind,context,question:text,messages:history})});const body=await response.json() as {answer?:string;error?:string;code?:string};if(!response.ok||!body.answer){setErrorCode(body.code||"");throw new Error(body.error||"Yanıt alınamadı.")}const next=[...history,...(text?[{role:"user" as const,content:text}]:[]),{role:"assistant" as const,content:body.answer}];setMessages(next);sessionStorage.setItem(storageKey,JSON.stringify(next))}catch(cause){setError(cause instanceof Error?cause.message:"Yanıt alınamadı.")}finally{setBusy(false)}}
  useEffect(()=>{if(started.current)return;started.current=true;void fetch("/api/ideas/assistant",{cache:"no-store"}).then(async response=>{const body=await response.json() as {configured?:boolean;tier?:"standard"|"gold"};setConfigured(Boolean(body.configured));setTier(body.tier==="gold"?"gold":"standard");if(!body.configured)return;try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||"[]") as Message[];if(saved.length){setMessages(saved);return}}catch{}void ask("",[])}).catch(()=>setConfigured(false))},[storageKey]);
  async function submit(event:FormEvent){event.preventDefault();const value=question.trim();if(!value||busy)return;setQuestion("");await ask(value)}
  if(configured!==true)return null;
  return <section className="mt-6 rounded-2xl border border-violet-200 bg-gradient-to-br from-violet-50 to-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-violet-700">✦ UIN Asistanı</p><h4 className="mt-1 font-black text-slate-950">{title} hakkında sor</h4></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-slate-500 shadow-sm">{tier==="gold"?"Gold · Web araştırması açık":"Standart · Kaydedilmez"}</span></div><div aria-live="polite" className="mt-4 space-y-3">{messages.map((message,index)=><div key={index} className={message.role==="assistant"?"whitespace-pre-wrap text-sm leading-6 text-slate-700":"ml-auto max-w-[88%] rounded-2xl bg-violet-700 px-4 py-3 text-sm text-white"}>{message.content}</div>)}{busy&&<p className="text-sm font-semibold text-violet-700">UIN Asistanı düşünüyor…</p>}{error&&<p role="alert" className={errorCode==="gold_research_required"?"rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900":"rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700"}>{error}</p>}</div><form onSubmit={submit} className="mt-4 flex gap-2"><input value={question} onChange={event=>setQuestion(event.target.value)} maxLength={800} placeholder={`${title} hakkında bir şey sor…`} className="min-w-0 flex-1 rounded-xl border border-violet-200 bg-white px-4 py-3 text-sm outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100"/><button disabled={busy||!question.trim()} className="rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white disabled:opacity-40">Sor</button></form><p className="mt-2 text-[11px] text-slate-500">Yalnızca {title} ile ilgili sorular yanıtlanır. {tier==="gold"?"Güncel sorularda internet araştırması kullanılabilir.":"Güncel ve yoğun internet araştırması Gold üyelik gerektirir."} Yanıtlar karta kaydedilmez.</p></section>
}
