import type {SupabaseClient} from '@supabase/supabase-js';
type Row=Record<string,any>;
export type Place={id:string;catalogItemId:string;title:string;coverUrl:string|null;wikiId:string;kind:string;countryId:string;country:string;cityId:string;city:string;district:string;adminKind?:string;parentTargetId?:string;sourceUrl:string;mapUrl:string};
const entityCache=new Map<string,{until:number;entity:Row}>();
export function currentValues(e:Row|undefined,p:string){const claims=(e?.claims?.[p]||[]).filter((c:Row)=>c.rank!=='deprecated'&&!c.qualifiers?.P582);const preferred=claims.filter((c:Row)=>c.rank==='preferred');return (preferred.length?preferred:claims).map((c:Row)=>c.mainsnak?.datavalue?.value).filter(Boolean)}
const name=(e:Row|undefined)=>e?.labels?.tr?.value||e?.labels?.en?.value||'';
export async function placeEntities(ids:string[]){const entities:Row={};const needed=[...new Set(ids)].filter(id=>/^Q[1-9]\d*$/.test(id));const missing=needed.filter(id=>{const hit=entityCache.get(id);if(hit&&hit.until>Date.now()){entities[id]=hit.entity;return false}return true});for(let off=0;off<missing.length;off+=50){const r=await fetch('https://www.wikidata.org/w/api.php?action=wbgetentities&format=json&props=claims%7Clabels&languages=tr%7Cen&ids='+missing.slice(off,off+50).join('|'),{headers:{'User-Agent':'UIN/1.0 place-geography'},signal:AbortSignal.timeout(10000),next:{revalidate:14400}});if(!r.ok)throw Error('Konum kaynağı alınamadı.');const d=await r.json();if(!d.entities)throw Error('Konum kaynağı alınamadı.');for(const [id,e] of Object.entries(d.entities)){entities[id]=e;if(entityCache.size>1500)entityCache.clear();entityCache.set(id,{until:Date.now()+14400000,entity:e as Row})}}return entities}
const isCity=(e:Row|undefined)=>!currentValues(e,'P31').some((v:Row)=>v.id==='Q2460358')&&currentValues(e,'P31').some((v:Row)=>['Q515','Q1549591','Q2716259','Q1637706','Q200250'].includes(v.id));
const isCountry=(e:Row|undefined)=>currentValues(e,'P31').some((v:Row)=>['Q6256','Q3624078'].includes(v.id));
export function placeGeo(id:string,entities:Row){const e=entities[id];if(!e)return null;let cityId=isCity(e)?id:'',district='';let layer=currentValues(e,'P131').map((v:Row)=>v.id);const districts=layer.filter((v:string)=>!isCity(entities[v])&&!isCountry(entities[v]));if(!cityId&&districts.length===1)district=name(entities[districts[0]]);const visited=new Set<string>([id]);for(let level=0;level<4&&!cityId;level++){const cities=[...new Set<string>(layer.flatMap((v:string)=>isCity(entities[v])?[v]:currentValues(entities[v],'P31').some((t:Row)=>t.id==='Q48336')?currentValues(entities[v],'P36').map((t:Row)=>t.id).filter((x:string)=>isCity(entities[x])):[]))];if(cities.length===1){cityId=cities[0];break}if(cities.length>1)break;if(level===0&&layer.length===1&&!isCountry(entities[layer[0]]))district=name(entities[layer[0]]);const next:string[]=[];for(const parent of layer){if(visited.has(parent))continue;visited.add(parent);next.push(...currentValues(entities[parent],'P131').map((v:Row)=>v.id))}layer=[...new Set(next)]}
 const countryIds=currentValues(e,'P17').map((v:Row)=>v.id).filter((v:string)=>isCountry(entities[v]));const countryId=countryIds.length===1?countryIds[0]:'';const coordinate=currentValues(e,'P625')[0];return {cityId,city:name(entities[cityId]),countryId,country:name(entities[countryId]),district,kind:isCountry(e)?'Ülke':isCity(e)?'Şehir':'Yer',sourceUrl:'https://www.wikidata.org/wiki/'+id,mapUrl:coordinate&&Number.isFinite(coordinate.latitude)&&Number.isFinite(coordinate.longitude)?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(coordinate.latitude+','+coordinate.longitude):''}}
export async function readPlaces(db:SupabaseClient):Promise<Place[]>{const visible:Row[]=[];for(let offset=0;offset<2000;offset+=200){const r=await db.rpc('get_uin_catalogue_v64',{p_query:null,p_limit:200,p_offset:offset,p_target_id:null});if(r.error)throw r.error;visible.push(...r.data||[]);if((r.data||[]).length<200)break}const ids=visible.map(c=>c.canonical_target_id);const items:Row[]=[];for(let off=0;off<ids.length;off+=200){const r=await db.from('seed_catalog_items').select('id,canonical_target_id,external_id,metadata').eq('item_kind','place').eq('status','active').in('canonical_target_id',ids.slice(off,off+200));if(r.error)throw r.error;items.push(...r.data||[])}for(const i of items.filter(i=>!i.metadata?.geonames_id&&!i.metadata?.wikidata_id&&!/^Q[1-9]\d*$/.test(String(i.external_id||'')))){const card=visible.find(c=>c.canonical_target_id===i.canonical_target_id);if(!card)continue;try{const r=await fetch('https://tr.wikipedia.org/w/api.php?action=query&format=json&prop=pageprops&titles='+encodeURIComponent(card.title),{signal:AbortSignal.timeout(8000),next:{revalidate:14400}});if(!r.ok)continue;const d=await r.json();const page=Object.values(d.query?.pages||{}).find((v:any)=>v.title?.toLocaleLowerCase('tr')===card.title.toLocaleLowerCase('tr')) as Row|undefined;const q=page?.pageprops?.wikibase_item;if(/^Q[1-9]\d*$/.test(q||'')&&page?.pageprops?.disambiguation===undefined)i.metadata={...i.metadata,wikidata_id:q}}catch{}}const sourceIds=items.map(i=>String(i.metadata?.wikidata_id||i.external_id||''));const entities=await placeEntities(sourceIds);let layer=sourceIds;for(let level=0;level<4;level++){const next=[...new Set(layer.flatMap(id=>[...currentValues(entities[id],'P131'),...currentValues(entities[id],'P17'),...currentValues(entities[id],'P36')].map((v:Row)=>v.id)))].filter(id=>id&&!entities[id]);if(!next.length)break;Object.assign(entities,await placeEntities(next));layer=next}
 const hierarchy=await db.rpc('get_place_hierarchy_v74',{p_target_ids:ids});if(hierarchy.error)throw hierarchy.error;
 const places:Place[]=items.filter((i,index,a)=>a.findIndex(x=>x.canonical_target_id===i.canonical_target_id)===index).map(i=>{const card=visible.find(c=>c.canonical_target_id===i.canonical_target_id)!;const wikiId=String(i.metadata?.wikidata_id||i.external_id||'');const geo=placeGeo(wikiId,entities);const lat=Number(i.metadata?.latitude),lng=Number(i.metadata?.longitude),globalKind=String(i.metadata?.global_place_kind||'');const sourceId=String(i.external_id||i.metadata?.source_external_id||'');const imported=globalKind?{kind:globalKind==='country'?'Ülke':'Şehir',countryId:`country:${i.metadata?.country_code||''}`,country:String(i.metadata?.country||''),cityId:globalKind==='city'?sourceId:'',city:globalKind==='city'?card.title:'',district:'',sourceUrl:String(i.metadata?.reference_url||''),mapUrl:Number.isFinite(lat)&&Number.isFinite(lng)?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(`${lat},${lng}`):''}:null;return {id:i.canonical_target_id,catalogItemId:i.id,title:card.title,coverUrl:card.catalog_cover_url||card.cover_url||null,wikiId:globalKind?sourceId:wikiId,...imported||geo||{kind:'Yer',countryId:'',country:'',cityId:'',city:'',district:'',sourceUrl:'',mapUrl:''},kind:imported?.kind||(geo?.kind==='Yer'?(i.metadata?.place_types?.[0]||'Yer'):geo?.kind||'Yer')}});return applyPlaceHierarchy(places,hierarchy.data||[])}

export function applyPlaceHierarchy(places:Place[],rows:Array<{target_id:string;place_hierarchy?:{kind?:string;parent_target_id?:string}|null}>):Place[]{const result=places.map(p=>{const h=rows.find(r=>r.target_id===p.id)?.place_hierarchy;const kind=h?.kind||p.kind;return {...p,kind,adminKind:h?.kind||'',parentTargetId:h?.parent_target_id||'',wikiId:p.wikiId||p.id,...(['İl','Şehir'].includes(kind)?{cityId:p.wikiId||p.id,city:p.title,district:''}:{})}});for(const p of result){const parent=result.find(x=>x.id===p.parentTargetId);if(parent&&['İl','Şehir'].includes(parent.kind)){p.cityId=parent.wikiId;p.city=parent.title;p.countryId=parent.countryId;p.country=parent.country;p.district=p.kind==='İlçe'?p.title:p.district}}return result}
