"use client";
import Link from "next/link";
import LifecycleCurrentDate from "../activities/LifecycleCurrentDate";
import { resolveActivityCover } from "../../utils/activityCover";

type Props={itemType:"intent"|"plan";title:string;activityName:string|null;categoryName:string|null;coverUrl:string|null;city:string|null;district:string|null;windowStart:string;windowEnd:string;expiredAt:string;roleLabel:string;participantCount:number;maxParticipants:number|null;personalBudget:number|null;committedBudget:number|null;targetBudget:number|null;visibility:string|null;notes:string|null;recruitmentStatus:string|null;matchingStatus:string|null;copiedFromIntentId:string|null;planId:string|null;sourceIntentId:string|null;canCreateAgain:boolean};
function money(v:number|null){return v===null?"Not set":`${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v)} TL`}
export default function TimelineExpiredPresentation(p:Props){
 const loc=[p.district,p.city].filter(Boolean).join(", "); const map=loc?`https://www.google.com/maps?q=${encodeURIComponent(loc)}&z=10&output=embed`:null; const cover=resolveActivityCover({planCoverUrl:p.coverUrl,categoryName:p.categoryName,activityName:p.activityName||p.title}); const href=p.planId?`/plans/${encodeURIComponent(p.planId)}/planning`:p.sourceIntentId?`/activities/${encodeURIComponent(p.sourceIntentId)}`:null;
 return <article className="relative flex h-full min-w-0 flex-col overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm">
  <div className="relative h-32 overflow-hidden bg-gray-950"><img src={cover} alt={`${p.title} cover`} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/10 to-black/40"/><div className="absolute inset-x-2.5 top-2.5 flex justify-between gap-2"><div className="flex gap-1"><span className="rounded-full bg-orange-100 px-2 py-0.5 text-[8px] font-bold uppercase text-orange-800">Expired</span><span className="rounded-full bg-black/65 px-2 py-0.5 text-[8px] font-semibold uppercase text-white">{p.roleLabel}</span></div></div><div className="absolute inset-x-0 bottom-0 px-3 pb-2.5"><p className="text-[8px] font-bold uppercase tracking-[0.11em] text-green-300">{p.categoryName??"Activity"}</p><h2 className="mt-0.5 line-clamp-2 text-[16px] font-bold leading-[1.1] text-white">{p.title}</h2></div></div>
  <div className="border-b border-black/5 p-2"><LifecycleCurrentDate targetStart={p.windowStart} targetEnd={p.windowEnd} expiredAt={p.expiredAt} status="expired" timezone="Europe/Istanbul" compact className="w-full"/></div>
  <div className="relative h-28 overflow-hidden border-b border-black/5 bg-gray-100">{map?<iframe title={`${p.title} approximate area`} src={map} className="absolute inset-0 h-full w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<div className="flex h-full items-center justify-center text-[10px] text-gray-400">No map</div>}{loc&&<span className="absolute bottom-2 left-2 max-w-[70%] truncate rounded-full bg-gray-950/80 px-2 py-1 text-[8.5px] font-semibold text-white">📍 {loc}</span>}</div>
  <div className="grid grid-cols-2 gap-1.5 p-2 text-[10px]">{[["Participants",`${p.participantCount} / ${p.maxParticipants??"∞"}`],["Visibility",p.visibility??"Not specified"],["Committed",money(p.committedBudget)],["Target",money(p.targetBudget??p.personalBudget)]].map(([l,v])=><div key={l} className="rounded-lg border border-gray-100 bg-white px-2 py-1.5 shadow-sm"><p className="truncate text-[7.5px] font-semibold uppercase text-gray-400">{l}</p><p className="mt-0.5 truncate font-semibold text-gray-900">{v}</p></div>)}</div>
  {p.notes&&<p className="mx-2 mb-2 line-clamp-2 rounded-lg bg-gray-50 px-2 py-1.5 text-[9.5px] leading-4 text-gray-600">{p.notes}</p>}
  <div className="mt-auto flex h-9 items-center gap-1 border-t border-gray-100 px-2">{href?<Link href={href} className="flex h-6 min-w-[58px] items-center justify-center rounded-md border border-gray-200 px-2 text-[9.5px] font-semibold text-gray-700">View</Link>:null}{p.canCreateAgain&&p.sourceIntentId?<Link href={`/onboarding?copyFrom=${encodeURIComponent(p.sourceIntentId)}`} className="flex h-6 min-w-[78px] items-center justify-center rounded-md bg-green-600 px-2 text-[9.5px] font-semibold text-white">Create Again</Link>:null}</div>
 </article>
}
