"use client";
import {useEffect,useState} from 'react';
import {bookUrl,type BookDetails as Data} from '@/utils/bookDetails';
type Choice={id:string;provider:string};
export default function BookDetails({targetId,id,provider,initialData}:{targetId?:string;id?:string;provider?:string;initialData?:Data}){
 const [data,setData]=useState<Data|null>(initialData||null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[choice,setChoice]=useState<Choice|null>(null),[candidates,setCandidates]=useState<(Choice&{title:string;description?:string})[]>([]);
 useEffect(()=>{const c=new AbortController();setData(initialData||null);setError('');setCandidates([]);const p=new URLSearchParams({...targetId?{targetId}:{},...id?{id}:{},...provider?{provider}:{},...choice||{}});void fetch('/api/books/details?'+p,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok){setCandidates(d.candidates||[]);throw Error(d.error||'Kitap detayları yüklenemedi.')}setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[targetId,id,provider,retry,choice,initialData]);
 return <section className="mt-5 space-y-5 rounded-2xl border border-gray-200 bg-white p-4"><h3 className="font-black">Kitap detayları</h3>{!data&&!error&&<p className="text-sm text-gray-500">Kitap bilgileri yükleniyor…</p>}{error&&<div role="status"><p className="text-sm text-gray-600">{error}</p><button type="button" onClick={()=>setRetry(n=>n+1)} className="mt-2 text-sm font-bold text-emerald-700">Tekrar dene</button></div>}{candidates.map(c=><button type="button" key={c.id} onClick={()=>setChoice({id:c.id,provider:c.provider})} className="block w-full rounded-xl border p-3 text-left"><span className="text-sm font-bold">{c.title}</span>{c.description&&<span className="mt-1 block text-xs text-gray-500">{c.description}</span>}</button>)}{data&&<>{data.image&&bookUrl(data.image)&&<img src={bookUrl(data.image)} alt={data.title} className="mx-auto max-h-80 w-full object-contain"/>}{data.subtitle&&<p className="text-sm font-semibold text-gray-600">{data.subtitle}</p>}{data.summary?<p className="whitespace-pre-line text-sm leading-7 text-gray-700">{data.summary}</p>:<p className="text-sm text-gray-500">Kaynakta bu kitap için açıklama bulunmuyor.</p>}<dl className="grid gap-3 sm:grid-cols-2">{data.facts.map(([label,value])=><div key={label} className="rounded-xl bg-gray-50 p-3"><dt className="text-xs text-gray-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl><div className="flex flex-wrap gap-3">{data.links.filter(l=>bookUrl(l.url)).map(l=><a key={l.url} href={bookUrl(l.url)} target="_blank" rel="noopener noreferrer" className="rounded-xl border border-emerald-200 px-4 py-3 text-sm font-bold text-emerald-700">{l.label} ↗</a>)}</div>{data.notice&&<p className="text-xs text-gray-500">{data.notice}</p>}<p className="text-[10px] text-gray-500">Kaynak: <a href={bookUrl(data.sourceUrl)} target="_blank" rel="noopener noreferrer" className="underline">{data.source}</a>{data.source.includes('Wikipedia')?' · Wikipedia: CC BY-SA; Wikidata: CC0.':'.'}</p></>}</section>;
}
