"use client";
import {useCallback,useEffect,useState} from "react";
import ClubProfileEditor from "@/components/clubs/ClubProfileEditor";
import TopicCardModal,{EventList,WantingList,type Detail} from "@/components/ideas/TopicCardModal";
import {resolveUinCardWords,type CardLabels} from "@/utils/uinCardLanguage";
import {clubTeamsWithVenues,fixtureDate,type ClubProfile,type ClubFixture,type ViewingContext} from "@/utils/clubProfile";
import {supabase} from "@/utils/supabase/client";
type View="overview"|"want"|"done"|"want_form"|"done_form"|"event_form"|"events";
export default function ClubProfilePage({targetId,title,subtitle,coverUrl,metadata,contentType,isAdmin=false}:{targetId:string;title:string;subtitle:string|null;coverUrl:string|null;metadata:Record<string,unknown>;contentType:{id:string;label:string;icon:string;ui_labels?:CardLabels};isAdmin?:boolean}){
 const [view,setView]=useState<View|null>(null),[choice,setChoice]=useState<{context:ViewingContext;date:string}|null>(null),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[edit,setEdit]=useState(false),[busy,setBusy]=useState(false);
 const profile=(metadata.club_profile||{}) as ClubProfile;
 const draftPosition=Number(metadata.cover_position_y??50);
 const draftCover=coverUrl||"";
 const [draft,setDraft]=useState<ClubProfile>(profile),[draftTitle,setDraftTitle]=useState(title),[draftSubtitle,setDraftSubtitle]=useState(subtitle||""),[draftAbout,setDraftAbout]=useState(typeof metadata.description==="string"?metadata.description:"");
 const words=resolveUinCardWords("club",contentType.ui_labels);
 const load=useCallback(async()=>{try{const response=await fetch("/api/ideas/"+targetId,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Kulüp topluluğu yüklenemedi.");setDetail(data)}catch(error){setError(error instanceof Error?error.message:"Kulüp topluluğu yüklenemedi.")}},[targetId]);
 useEffect(()=>{void load()},[load]);
 async function follow(){if(!detail?.viewerId){setError("Kulübü takip etmek için giriş yapmalısın.");return}setBusy(true);setError("");const {error}=await supabase.rpc("save_my_club_follow_v60",{p_target_id:targetId,p_follow:!detail?.clubContext?.following});if(error)setError(error.message);else await load();setBusy(false)}
 async function save(){setBusy(true);setError("");try{const response=await fetch("/api/ideas/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update",canonicalTargetId:targetId,title:draftTitle,itemKind:contentType.id,creatorName:draftSubtitle,coverUrl:draftCover,coverPositionY:draftPosition,description:draftAbout,referenceUrl:metadata.reference_url||"",clubProfile:draft})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Profil kaydedilemedi.");window.location.reload()}catch(error){setError(error instanceof Error?error.message:"Profil kaydedilemedi.");setBusy(false)}}
 async function uploadLogo(file:File){setBusy(true);setError("");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/ideas/cover",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Logo yüklenemedi.");setDraft({...draft,logo_url:data.url})}catch(error){setError(error instanceof Error?error.message:"Logo yüklenemedi.")}finally{setBusy(false)}}
 function open(view:View){setChoice(null);setView(view)}
 function plan(fixture:ClubFixture){setChoice({context:{fixture_id:fixture.id,match_start_at:fixture.start_at,sport:fixture.sport,mode:"undecided",match:title+" – "+fixture.opponent},date:fixture.start_at?.slice(0,10)||""});setView("event_form")}
 const fixtures=[...(profile.fixtures||[])].sort((a,b)=>(fixtureDate(a.start_at)?.getTime()||Infinity)-(fixtureDate(b.start_at)?.getTime()||Infinity));
 const upcoming=fixtures.filter(f=>!fixtureDate(f.start_at)||fixtureDate(f.start_at)!.getTime()>=Date.now());const past=fixtures.filter(f=>fixtureDate(f.start_at)&&fixtureDate(f.start_at)!.getTime()<Date.now());
 function fixtureRows(rows:ClubFixture[],active:boolean){return rows.map(f=><article key={f.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border p-4"><div><p className="text-xs font-bold text-emerald-700">{[f.sport,f.competition].filter(Boolean).join(" · ")}</p><h3 className="mt-1 font-black">{title} – {f.opponent||"Rakip henüz belli değil"}</h3><p className="mt-2 text-sm text-slate-500">{fixtureDate(f.start_at)?new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Istanbul"}).format(fixtureDate(f.start_at)!):"Tarih henüz belli değil"}{f.venue&&" · "+f.venue}</p></div>{active?<button onClick={()=>plan(f)} className="rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white">Birlikte izleyelim</button>:<span className="text-xs text-slate-500">Tarihi geçti</span>}</article>)}
 return <>
 <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="p-5 md:p-8"><div className="flex flex-wrap items-center gap-5">{profile.logo_url?<img src={profile.logo_url} alt="Kulüp logosu" className="uin-logo h-24 w-24 rounded-2xl border bg-white p-2 object-contain"/>:<span className="grid h-24 w-24 place-items-center rounded-2xl bg-slate-100 text-4xl font-black">{title.charAt(0)}</span>}<div className="min-w-0 flex-1"><span className="text-xs font-black uppercase tracking-widest text-emerald-700">Spor kulübü</span><h1 className="mt-1 text-3xl font-black">{title}</h1>{subtitle&&<p className="mt-1 text-slate-500">{subtitle}</p>}<p className="mt-2 text-sm text-slate-500">{[profile.founded_year&&"Kuruluş · "+profile.founded_year,profile.city,profile.colors].filter(Boolean).join(" · ")}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||!detail} onClick={()=>void follow()} className="rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 font-black text-emerald-800">{detail?.clubContext?.following?"✓ Takip ediyorum":"＋ Takip et"}</button>{isAdmin&&<button onClick={()=>{setError("");setEdit(true)}} className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-black text-amber-800">✎ Profili düzenle</button>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>open("want_form")} className="rounded-xl bg-emerald-600 p-4 font-black text-white">{words.want}</button><button onClick={()=>open("event_form")} className="rounded-xl bg-violet-700 p-4 font-black text-white">{words.event}</button></div><div className="mt-5 grid grid-cols-2 gap-3 text-center md:grid-cols-4">{[{label:"Takipçi",count:detail?.clubContext?.follower_count,href:"#topluluk"},{label:words.wanting,count:detail?.people.filter(p=>p.is_current!==false).length,href:"#istekler"},{label:words.doers,count:detail?.reviews.length,href:"#deneyimler"},{label:"Aktif buluşma",count:detail?.events.filter(e=>eventActive(e)).length,href:"#bulusmalar"}].map(item=><a key={item.label} href={item.href} className="rounded-xl bg-slate-50 p-3 hover:bg-emerald-50"><span className="block text-xl font-black">{item.count??"—"}</span><span className="mt-1 block text-xs text-slate-500">{item.label}</span></a>)}</div></div><nav className="flex gap-5 overflow-x-auto border-t px-6 py-4 text-sm font-bold text-slate-600">{[["bulusmalar","Etkinlikler"],["istekler","Maç izlemek isteyenler"],["hakkinda","Hakkında"],["branslar","Branşlar"],["karsilasmalar","Karşılaşmalar"]].map(([id,label])=><a key={id} href={"#"+id} className="shrink-0 hover:text-emerald-700">{label}</a>)}</nav></article>
 {error&&!edit&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
 <section id="bulusmalar" className="mt-6 scroll-mt-6 rounded-3xl border bg-white">{detail?<EventList events={detail.events} targetTitle={title}/>:<p className="p-6 text-sm text-slate-500">Buluşmalar yükleniyor…</p>}</section>
 <section id="topluluk" className="mt-6 scroll-mt-6 rounded-3xl border bg-white"><div id="istekler">{detail&&<WantingList people={detail.people} events={detail.events} viewerId={detail.viewerId} targetId={targetId} title={words.wanting} targetTitle={title} contentType={contentType} onSelectType={()=>{window.location.href="/ideas?kind=club"}}/>}</div><div id="deneyimler" className="border-t p-6"><h2 className="text-xl font-black">Maç deneyimleri</h2><div className="mt-4 grid gap-3">{detail?.reviews.length?detail.reviews.map(review=><article key={review.seed_id} className="rounded-xl border p-4"><a href={review.username?"/u/"+review.username:"/people/"+review.user_id} className="flex items-center gap-3 font-bold text-emerald-800">{review.avatar_url&&<img src={review.avatar_url} alt="" className="h-9 w-9 rounded-full object-cover"/>}{review.full_name}</a>{review.rating&&<p className="mt-2 text-xs text-slate-500">★ {review.rating}/10</p>}{review.body&&<p className="mt-3 whitespace-pre-line text-sm text-slate-600">{review.body}</p>}</article>):<p className="text-sm text-slate-500">Henüz maç deneyimi paylaşılmamış.</p>}</div></div></section>
 <section id="hakkinda" className="mt-6 scroll-mt-6 rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Hakkında</h2><p className="mt-4 whitespace-pre-line leading-7 text-slate-600">{typeof metadata.description==="string"&&metadata.description||"Henüz tanıtım eklenmemiş."}</p>{profile.history&&<><h3 className="mt-6 font-black">Tarihçe</h3><p className="mt-3 whitespace-pre-line leading-7 text-slate-600">{profile.history}</p></>}<div className="mt-5 flex flex-wrap gap-2">{profile.website&&<a href={profile.website} target="_blank" rel="noopener noreferrer" className="rounded-xl border px-4 py-2 text-sm font-bold text-emerald-700">Resmi site ↗</a>}{profile.social_links?.map(link=><a key={link.id} href={link.url} target="_blank" rel="noopener noreferrer" className="rounded-xl border px-4 py-2 text-sm font-bold">{link.label} ↗</a>)}</div></section>
 <section id="branslar" className="mt-6 scroll-mt-6 rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Branşlar ve takımlar</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{profile.teams?.length?clubTeamsWithVenues(profile).map(team=><article key={team.id} className="flex gap-3 rounded-2xl border p-4">{team.logo_url&&<img src={team.logo_url} alt={team.name+" logosu"} className="h-14 w-14 object-contain"/>}<div><p className="text-xs font-black text-emerald-700">{team.sport}{team.division&&" · "+team.division}</p><h3 className="mt-1 font-black">{team.name||team.sport+" takımı"}</h3>{team.league&&<p className="mt-2 text-sm text-slate-500">{team.league}</p>}{team.venue&&<p className="mt-1 text-sm text-slate-500">{team.venue}</p>}{team.map_url&&<a href={team.map_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-sm font-bold text-emerald-700">📍 Haritada aç ↗</a>}</div></article>):<p className="text-sm text-slate-500">Henüz branş bilgisi eklenmemiş.</p>}</div></section>
 <section id="karsilasmalar" className="mt-6 scroll-mt-6 rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Yaklaşan karşılaşmalar</h2><div className="mt-4 grid gap-3">{upcoming.length?fixtureRows(upcoming,true):<p className="text-sm text-slate-500">Henüz yaklaşan karşılaşma eklenmemiş.</p>}</div>{past.length>0&&<details className="mt-5 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-bold">Geçmiş karşılaşmalar · {past.length}</summary><div className="mt-3 grid gap-3">{fixtureRows(past,false)}</div></details>}</section>
 {edit&&<div className="fixed inset-0 z-[150] overflow-y-auto bg-black/60 p-4"><form onSubmit={e=>{e.preventDefault();void save()}} className="mx-auto my-5 max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-black">Kulüp profilini düzenle</h2><button type="button" onClick={()=>setEdit(false)} className="rounded-full bg-slate-100 px-3 py-2">×</button></div><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Kulübün tam adı<input required maxLength={240} value={draftTitle} onChange={e=>setDraftTitle(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Kısa adı<input value={draftSubtitle} onChange={e=>setDraftSubtitle(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Tanıtım<textarea maxLength={4000} rows={4} value={draftAbout} onChange={e=>setDraftAbout(e.target.value)} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Logo dosyası yükle<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadLogo(file)}} className="mt-1 w-full rounded-xl border p-3"/><span className="mt-1 block text-xs font-normal text-slate-500">Dış site bağlantıyı engelliyorsa logoyu dosya olarak yükle.</span></label><ClubProfileEditor value={draft} onChange={setDraft}/></div>{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-5 w-full rounded-xl bg-emerald-600 p-4 font-black text-white">{busy?"Kaydediliyor…":"Profili kaydet"}</button></form></div>}
 {view&&<TopicCardModal isClub selected={{catalogItemId:"",canonicalTargetId:targetId,title,subtitle,coverUrl,initialView:view,initialViewing:choice?.context,initialStartDate:choice?.date}} contentType={contentType} onSelectType={()=>{window.location.href="/ideas?kind=club"}} wantLabel={words.want} doneLabel={words.done} wantingLabel={words.wanting} doersLabel={words.doers} targetAction={words.action} eventButtonLabel={words.event} onClose={()=>{setView(null);void load()}}/>}
 </>;
}
function eventActive(event:Detail["events"][number]){if(["completed","cancelled","canceled"].includes(event.status||"")||["completed","cancelled"].includes(event.plan_status||""))return false;const today=new Date().toLocaleDateString("sv-SE",{timeZone:"Europe/Istanbul"});return (event.end_date||event.start_date)?.slice(0,10)>=today;}
