import {NextRequest,NextResponse} from 'next/server';
import {createClient} from '@/utils/supabase/server';
import {bookJson,googleBookDetails,wikiBookDetails,searchWikiBooks} from '@/utils/bookDetails';
export async function GET(req:NextRequest){try{
 let id=req.nextUrl.searchParams.get('id')||'',provider=req.nextUrl.searchParams.get('provider')||'';const targetId=req.nextUrl.searchParams.get('targetId');let title='',creator='';let cached:ReturnType<typeof googleBookDetails>|null=null;
 if(targetId){if(!/^[0-9a-f-]{36}$/i.test(targetId))return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const db=await createClient();const profile=await db.rpc('get_uin_card_profile_v60',{p_target_id:targetId});if(profile.error||!profile.data?.title)return NextResponse.json({error:'Kart bulunamadı.'},{status:404});const result=await db.from('seed_catalog_items').select('external_id,external_source,item_kind,metadata').eq('canonical_target_id',targetId).eq('status','active');const item=result.data?.find(x=>x.item_kind==='book')||result.data?.[0];const meta={...(item?.metadata||{}),...(profile.data.metadata||{})};const type=await db.from('uin_content_types').select('base_kind').eq('id',String(meta.content_type_id||item?.item_kind||'')).maybeSingle();if(item?.item_kind!=='book'&&type.data?.base_kind!=='book')return NextResponse.json({error:'Bu kart bir kitap değil.'},{status:400});title=profile.data.title;creator=profile.data.creator_name||'';if(item?.external_source==='google_books'){cached=meta.book_details||googleBookDetails({id:item.external_id,volumeInfo:{title,authors:meta.authors||[creator].filter(Boolean),description:meta.description,publisher:meta.publisher,publishedDate:meta.published_date,pageCount:meta.page_count,language:meta.language,categories:meta.categories,industryIdentifiers:meta.isbn||[{type:'ISBN_13',identifier:meta.isbn_13},{type:'ISBN_10',identifier:meta.isbn_10}],imageLinks:{thumbnail:profile.data.cover_url},infoLink:meta.info_url||meta.source_url}})}if(!id){provider=String(meta.source_provider||item?.external_source||'');id=String(meta.google_books_id||meta.google_books_volume_id||meta.wikidata_id||meta.source_external_id||item?.external_id||'')}}
 if(provider==='google_books'&&/^[A-Za-z0-9_-]{1,100}$/.test(id)){try{return NextResponse.json(googleBookDetails(await bookJson('https://www.googleapis.com/books/v1/volumes/'+encodeURIComponent(id))))}catch{if(!title)throw Error('Kitap kaynağı yüklenemedi.')}}
 if(provider==='wikidata'&&/^Q[1-9]\d*$/.test(id))return NextResponse.json(await wikiBookDetails(id));
 if(!title)return NextResponse.json({error:'Kaynakta bir kitap seç.'},{status:400});
 const candidates=await searchWikiBooks(title).catch(()=>[]);const normalized=(s:string)=>s.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/\p{M}/gu,'').replace(/ı/g,'i').replace(/[^\p{L}\p{N}]/gu,'');const exact=candidates.filter(c=>normalized(c.title)===normalized(title));
 const details=await Promise.all(exact.slice(0,3).map(async c=>{try{return await wikiBookDetails(c.id)}catch{return null}}));
 const authorParts=creator.split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>1).map(normalized);const matches=details.filter(d=>d&&authorParts.length>=2&&authorParts.every(part=>normalized(d.facts.find(f=>f[0]==='Yazar')?.[1]||'').includes(part)));
 if(matches.length===1){const d=matches[0]!;if(cached)return NextResponse.json({...cached,summary:cached.summary||d.summary,source:cached.summary?cached.source:'Google Books (kayıtlı baskı) / Wikipedia',links:[...cached.links,...d.links],notice:'Google Books şu anda yanıt vermiyor; kayıtlı baskı bilgileri gösteriliyor.'+(!cached.summary&&d.summary?' Açıklama Wikipedia kaynağından alınmıştır.':'')});return NextResponse.json(d)}
 if(cached&&cached.facts.length)return NextResponse.json({...cached,notice:'Google Books şu anda yanıt vermiyor; bu karta kayıtlı baskı bilgileri gösteriliyor.'});
 // A title alone cannot reliably identify a legacy book or its edition.
 return NextResponse.json({error:'Bu eski kartın kaynak bağlantısını kesinleştirmek için doğru kitabı seç.',candidates:(exact.length?exact:candidates).map(c=>({...c,provider:'wikidata'}))},{status:409});
 }catch{return NextResponse.json({error:'Kitap detayları şu anda alınamadı. Tekrar deneyebilirsin.'},{status:502})}}
